### ISSUE TITLE
[Brasil] Quality Assurance na BUILDERS

### ISSUE THREAD

**Issue by queroou2** [qa-brasil/vagas#1049]
## Descrição da vaga

No papel de Test Analyst, a pessoa Builder trabalhará em equipes para fornecer soluções robustas e escaláveis em gestão de testes funcionais. Deverá definir estratégia, plano de testes e execução de testes funcionais com base no escopo do projeto, sempre pensando em melhores práticas de testes para aplicações em multiplataformas.

## Local de trabalho

- 100% Remoto

**Requisitos da vaga**

**Obrigatórios**
    Métodos de Qualidade de Software;
    Metodologia Ágil;
    Testes em multiplataformas, criação e execução de testes manuais para Mobile, API e Web;
    Documentação em plataformas, como Jira.

**Desejáveis**
Elaborar casos de testes com a técnica BDD e ATDD;
Ter foco na usabilidade e acessibilidade do produto;
Conhecimento em ferramentas de gerenciamento de testes (Qase, Zephyr, XRay, etc)

**Diferenciais**
- Experiência com automação

**O que nós oferecemos?**

    Atuação 100% remota;
    Parceria com coworking em São Paulo;
    Webnars semanais para expandir ainda mais seu conhecimento;
    Participar de um processo único de geração de valor;
    Contribuir na criação de métodos disruptivos;
    Possibilidade de profit share de novos negócios.

**Conhece o Movimento Builders?**

Você pode pensar que não nos conhece, mas provavelmente já teve contato com uma das nossas diversas soluções criadas especialmente para grandes clientes nacionais de diferentes segmentos. Essas soluções são criadas pelas mãos de pessoas empreendedoras, apaixonadas por inovação que geram valor impactando pessoas e negócios. 

Ao ingressar na Builders, você fará parte de um movimento que idealiza, cocria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você curte desafios, aqui é o seu lugar! 

**Como se candidatar**

**Se identificou? Candidate-se neste link:** https://jobs.kenoby.com/sejabuilder/job/senior-test-analyst-cod-793-remoto/62bd8da778c31d51831c32af?utm_source=website

**Tempo médio de feedbacks**

Costumamos enviar feedbacks em até 7 dias após cada processo.

E-mail para contato em caso de não haver resposta: ana.souza@plataformabuilders.io Labels

- CLT
- PJ
- Sênior
- Especialista

- Remoto

- Brasil

**Comment by mariana-marques1991** [comment]
Vaga cancelada!

**Comment by queroou2** [comment]
> ## Descrição da vaga
> 
> No papel de Test Analyst, a pessoa Builder trabalhará em equipes para fornecer soluções robustas e escaláveis em gestão de testes funcionais. Deverá definir estratégia, plano de testes e execução de testes funcionais com base no escopo do projeto, sempre pensando em melhores práticas de testes para aplicações em multiplataformas.
> ## Local de trabalho
> 
>     * 100% Remoto
> 
> 
> **Requisitos da vaga**
> 
> **Obrigatórios** Métodos de Qualidade de Software; Metodologia Ágil; Testes em multiplataformas, criação e execução de testes manuais para Mobile, API e Web; Documentação em plataformas, como Jira.
> 
> **Desejáveis** Elaborar casos de testes com a técnica BDD e ATDD; Ter foco na usabilidade e acessibilidade do produto; Conhecimento em ferramentas de gerenciamento de testes (Qase, Zephyr, XRay, etc)
> 
> **Diferenciais**
> 
>     * Experiência com automação
> 
> 
> **O que nós oferecemos?**
> 
> ```
> Atuação 100% remota;
> Parceria com coworking em São Paulo;
> Webnars semanais para expandir ainda mais seu conhecimento;
> Participar de um processo único de geração de valor;
> Contribuir na criação de métodos disruptivos;
> Possibilidade de profit share de novos negócios.
> ```
> 
> **Conhece o Movimento Builders?**
> 
> Você pode pensar que não nos conhece, mas provavelmente já teve contato com uma das nossas diversas soluções criadas especialmente para grandes clientes nacionais de diferentes segmentos. Essas soluções são criadas pelas mãos de pessoas empreendedoras, apaixonadas por inovação que geram valor impactando pessoas e negócios.
> 
> Ao ingressar na Builders, você fará parte de um movimento que idealiza, cocria e conecta pessoas. Desfrutando de um ambiente colaborativo que propicia oportunidade de crescimento exponencial. Se você curte desafios, aqui é o seu lugar!
> 
> **Como se candidatar**
> 
> **Se identificou? Candidate-se neste link:** https://jobs.kenoby.com/sejabuilder/job/senior-test-analyst-cod-793-remoto/62bd8da778c31d51831c32af?utm_source=website
> 
> **Tempo médio de feedbacks**
> 
> Costumamos enviar feedbacks em até 7 dias após cada processo.
> 
> E-mail para contato em caso de não haver resposta: [ana.souza@plataformabuilders.io](mailto:ana.souza@plataformabuilders.io) Labels
> 
>     * CLT
> 
>     * PJ
> 
>     * Sênior
> 
>     * Especialista
> 
> 
>     * Remoto
> 
> 
>     * Brasil
