### ISSUE TITLE
[São Paulo] QA na Extractta

### ISSUE THREAD

**Issue by isatelesmar** [qa-brasil/vagas#1067]
## Local de trabalho

- 100% Remoto

## Requisitos da vaga

**1. Conhecimentos Específicos de Tecnologia:**
React: Entender os conceitos de componentes, estado (state), props, ciclo de vida de componentes,
hooks, e como testar aplicações React (ex.: usando Jest e React Testing Library).
Node.js: Familiaridade com o ambiente de execução Node.js, incluindo testes de APIs RESTful ou
GraphQL (usando ferramentas como Mocha, Chai, Jest, Supertest).
GCP (Google Cloud Platform): Conhecimento em serviços da GCP usados pela equipe, como Compute
Engine, App Engine, Cloud Functions, Firebase, BigQuery, etc., e como eles impactam a arquitetura e os
testes de aplicações.
**2. Ferramentas de Testes Automatizados e Frameworks:**
Jest: Para testes unitários e de integração tanto em React quanto em Node.js.
Selenium, Cypress, ou Puppeteer: Para testes end-to-end (E2E) de aplicações web.
Postman e Newman: Para testes de API.
**3. Práticas de CI/CD:**
GitHub Actions, GitLab CI/CD, ou Jenkins: Conhecimento em integração e entrega contínuas,
configurando pipelines que incluem etapas de teste automatizado.
Docker: Entender o uso de containers para criar ambientes consistentes para testes e produção.
Terraform ou Google Cloud Deployment Manager: Para infraestrutura como código (IaC), essencial em
ambientes cloud.
**4. Controle de Qualidade e Estratégias de Teste:**
Conhecimento em diferentes tipos de testes (unitários, integração, sistema, aceitação do usuário) e
quando aplicá-los.
Estratégias de teste como Test Driven Development (TDD) e Behavior Driven Development (BDD).
Gestão de bugs e ferramentas de rastreamento (ex.: JIRA).
**5. Segurança e Desempenho:**
Testes de segurança: Conhecimentos básicos sobre OWASP Top 10, e ferramentas de teste de
segurança.
Testes de desempenho e carga: Uso de ferramentas como JMeter, LoadRunner, ou ferramentas
específicas da cloud para testar a escalabilidade e a resiliência das aplicações

## Forma de contratação

PJ

## Benefícios da empresa

- 15 dias de descanso remunerado

## Sobre a empresa

A Extractta atua no mercado desde 2005, somos especializados em soluções Big Data, Integração de Dados e outsourcing.

## Como se candidatar

- Por favor envie um email para isabele.martins@extractta.com.br com seu CV anexado - Enviar no assunto: Vaga de QA

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

## Labels

- PJ
- Pleno
- Sênior
- Remoto

**Comment by isatelesmar** [comment]
Nova vaga para QA Pleno/Sênior em aberto!!

**Comment by lucas-olvra** [comment]
Cv enviado!
