### ISSUE TITLE
[Belo Horizonte] QA na Sambatech

### ISSUE THREAD

**Issue by karemandrade** [qa-brasil/vagas#11]
## Descrição da vaga

- Responsável pelo planejamento e execução de todas as atividades de QA: participação no processo de definição de escopo e requisitos de projetos, criação de planos e massas de testes, execução de testes manuais e automatizados, geração de evidências e relatórios de testes, pesquisa e análise de bugs, validação de sistemas, acompanhamento de deploys;
- Acompanhamento de disponibilidade, estabilidade e desempenho dos sistemas corporativos em ambiente de produção, reportando incidentes e atuando na melhoria constante de tais sistemas;
- Revisão e atualização constantemente dos processos e procedimentos de QA, além de garantir o alinhamento desses com os demais processos da empresa. 

## Local

Belo Horizonte - Santa Lúcia

## Benefícios

- Plano de saúde
- VR / VA
- Vale transporte
- Gympass
- Demais

## Requisitos

**Desejáveis:**
- Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou áreas afins;
- Experiência mínima de 1 anos em cargos similares;
- Experiência com manipulação de dados em SQL;
- Ter pensamento crítico e atenção a detalhes;
- Experiência em Testes Exploratórios e Testes Funcionais;
- Conhecer e aplicar técnicas e conceitos de qualidade de software;
- Metodologias ágeis (preferencialmente, Scrum);
- Habilidade de se comunicar e facilidade para trabalhar em equipe.

**Diferenciais:**
- Experiência com frameworks de automação de testes, tais como Selenium e JUnit;
- Conhecimento e experiência com práticas de uma cultura DevOps, visando otimizações para um fluxo de entrega contínua;
- Conhecimento intermediário/avançado em alguma linguagem de programação, preferencialmente Java, Javascript ou Python.

## Nossa empresa

Nossos Analistas de Qualidade e Teste de Software (a.k.a, Analistas de QA) contribuem para a evolução de produtos que entregam conteúdo de vídeo e áudio para milhões de pessoas e nos ajudam a aproximar da nossa missão de acelerar o sucesso dos negócios de produtores de conteúdo na era pós-texto. 
Como Analista de QA, você trabalhará em produtos críticos para o negócio da Samba e terá a oportunidade de aprender com pessoas incríveis e de abraçar novos desafios na medida em que você e o nosso negócio se desenvolvem. Nossos engenheiros de software são versáteis, demonstram qualidades de liderança e são apaixonados pela resolução de problemas por meio de tecnologia.

## Como se candidatar

Cadastre-se em 
https://jobs.kenoby.com/sambatech-carreiras/job/analista-de-qualidade-e-teste-de-software/5e2f0ec58ade0d07c2f45d5d

## Labels

- CLT
- Jr.
- Pleno
- Senior

**Comment by AlvaroHPess** [comment]
@karemandrade e @PauloGoncalvesBH  o link para cadastro está quebrado.
