### ISSUE TITLE
[São Paulo] QA na Zup

### ISSUE THREAD

**Issue by NAIDSON10** [qa-brasil/vagas#112]
Oi, pessoal! Nós da Intera temos uma ótima oportunidade para você que é analista de testes. Estamos em busca de talentos que tenham experiência consolidada com Testlink e Jira, nível sênior, para integrar o time da Zup.

A Zup é uma empresa de produtos digitais que impactam diretamente no modelo de negócio dos clientes. Ajudando na transformação digital bem como na transformação cultural de várias outras empresas. Para acompanhar a decolagem dessa navi, que cada vez mais alça voos maiores, estamos buscando uma pessoa com experiência nessas áreas e disposto a mandar vê nesse novo desafio!!

Queremos muito encontrar alguém que possua a partir de 5 anos de experiência na área e ter atuado em consultoria. O regime de contratação será CLT e como benefícios: PLR - Participação dos Lucros e Resultados, Banco de horas, Auxilio Quarentena,  Vale transporte; Vale Refeição/Alimentação; Plano de Saúde; Plano odontológico, GymPass, Seguro de Vida, Auxílio Creche, entre outros. 

Tem vontade de criar algo novo juntamente com a Zup ? Veja mais informações nesse link: https://byintera.in/16l  Desejo um ótimo dia e um sorrido de orelha a orelha =D

**Comment by JeffersonBru** [comment]
Presencial ou remoto?
