### ISSUE TITLE
[Remoto] QA Automation Tester + 4XP @ Mollica IT

### ISSUE THREAD

**Issue by raissaime** [qa-brasil/vagas#1158]
## Descrição da vaga

Buscando projetos internacionais?

Então vem com a Mollica IT e encontre a oportunidade certa pra dar match!

Estamos em busca de profissionais inovadores e criativos, que tenham paixão em crescer, evoluir e  aprender.

## Local de trabalho

- Você poderá escolher as seguintes opções:

- Alphaville - SP - Presencial ou Híbrido;
- Londrina - PR - Presencial ou Híbrido;
- 100% Home Office.

## Missão

- Atuar com automação de testes;
- Ser responsável pelos processos de QA. 

## Requisitos da vaga

**Obrigatórios**

- Experiência com as tecnologias de teste: Selenium, Cypress, Postman, Cucumber, BDD, Protractor ou JMeter;
- Experiência em processos de QA (teste de unidade / teste de integração, UAT, automação, documentação, controle de versão);
- Experiência em APIs REST, incluindo ferramentas para documentação (Swagger/Postman);
- Conhecimentos em frontend web responsivo/desenvolvimento de aplicativo de página única usando JavaScript modular;
- Conhecimentos em testes de aplicativos da Web em vários navegadores e dispositivos usando ferramentas de teste automatizadas;
- Experiência em APi e automação da interface do usuário;
- Experiência em testes manuais ou exploratórios;
- Experiência em projetos utilizando práticas e metodologias ágeis;
- Obrigatório Graduação completa em áreas de tecnologia;

🌎 **Idioma:**
- _Inglês Avançado para conversação (Haverá etapa de entrevista nesse idioma)._

**Desejáveis**
- Experiência em testar sistemas de persistência de dados usando SQL e NoSQL DBMS (MSSQL, PostgreSQL, Dynamo);
- Experiência com Devops, CI/CD, AWS/Cloud;
- Experiência com Github ou outro repositório;

## Forma de contratação

CLT

## Benefícios da empresa

✔️Assistência Médica para colaboradores e dependentes com abrangência nacional da Bradesco ou Unimed

✔️Assistência Odontológica com abrangência nacional

✔️Vale Refeição ou Vale Alimentação (a escolha do colaborador)

✔️Auxílio creche

✔️Seguro de Vida para associados e dependentes

✔️Gympass para associados e dependentes

✔️EAP (Employee Assistance Program) com os seguintes serviços: Assistência Financeira, Assistência Jurídica, Assistência Social, Assistência Psicológica (24 horas – 7 dias por semana).

✔️Descontos e tarifas diferenciadas junto a Universidades (Mackenzie, SENAC, FIA, FIAP e BBS Business School) e escola de idiomas (CNA, Cultura Inglesa, Wizard, CCAA, Indeed).

✔️Descontos em pacotes de tarifas e taxas diferenciadas para Bancos Itaú e Bradesco

✔️Opção de crédito consignado, com desconto diretamente no salário do colaborador

✔️Programa de reembolso de algumas certificações externas

✔️Treinamento: A TCS oferece plataforma de treinamento e desenvolvimento a distância e presencias, em soft skills, tecnologias e domínios em mais de 15.000 temas.

✔️Premiação por tempo de casa: A TCS premia associados por seu comprometimento e lealdade durante o período em que trabalhar na empresa (3, 5 e 10 anos e cada 5 anos posteriormente).

✔️Prêmio de indicação de novos colaboradores - recebendo um bônus para cada nova contratação.

✔️TCS Fit4life - Programa para incentivar a prática de exercício físico junto a seus associados, com agenda de treinamentos funcionais online.

✔️Experiência internacional: Dependendo de seus conhecimentos e das demandas do negócio você pode se candidatar a vagas no exterior (dentro e fora da América Latina).

✔️Entre outros;

## Range Salarial

A vaga paga entre R$ 11 e 15K.

## Sobre a empresa

O que nós fazemos? Como líderes globais em serviços de TI, soluções digitais e negócios, fazemos parcerias com clientes para simplificar, fortalecer e transformar, ajudando clientes a criar o futuro!

Somos uma das 5 principais empresas de tecnologia na Top 100 do mundo da Forbes, o maior grupo multinacional de negócios da Índia, com instalações de fabricação em mais de 40 países com presença operacional em 180 países. Suas operações são apoiadas por uma pilha de mais de 80 aplicativos SAP e mais de 1900 Aplicativos não SAP.

Oferecemos perspectiva de crescimento, e oportunidade de aprendizado e certificações. Desejamos construir a próxima geração de sistemas e fábricas que envolvem as mais recentes Tecnologias e migrando para a Nuvem nos próximos 2 anos. Possuímos desenvolvimento Agile, Devops e oportunidades em 60 países.

A TCS combina experiência em tecnologia e inteligência de negócios para catalisar mudanças e entregar resultados.

## Como se candidatar

https://tally.so/r/w7Nj19

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 07 dias após cada processo.

## Labels

- CLT
- Pleno
- Sênior

- Presencial
- Remoto

- São Paulo / Londrina

**Comment by afsarali-pg** [comment]
Interested
