### ISSUE TITLE
[Remoto] Analista de Testes @ Mollica IT

### ISSUE THREAD

**Issue by raissaime** [qa-brasil/vagas#1159]
## Descrição da vaga

Buscando projetos inovadores?

Então vem com a Mollica IT e encontre a oportunidade certa pra dar match!

Estamos em busca de profissionais inovadores e criativos, que tenham paixão em crescer, evoluir e  aprender.

## Local de trabalho

- 100% Remoto

## Requisitos da vaga

**Obrigatórios**
- Experiência profissional comprovada com Testes;

- Experiência com Postman;

- Conhecimentos em Javascript para scripts de testes;

- Experiência com testes funcionais e exploratórios;

- Experiência em levantamento de cenários;

- Obrigatório Graduação completa na área de TI.

**Diferenciais**

- Experiência em Selenium;
- Conhecimentos em Python;
- Conhecimentos em automação de testes em frontend e de APIs (serviços).

## Forma de contratação

CLT

## Benefícios da empresa
✔️ Vale Alimentação e/ou Vale Refeição de R$ 24,00/dia

✔️ Assistência Médica Unimed ;

✔️ Assistência Odontológica Bradesco;

✔️ Descontos em cursos, graduações e pós graduações com parceiros;

✔️ Descontos em entretenimento, lazer e compras – Lincard;

✔️ ECX Farmácia: Compra de medicamentos com prazo de pagamento em até 45 dias (valor da compra debitado diretamente na folha de pagamento);

✔️ Programa Auster (Assistência Psicológica/Nutricional/Fisioterapêutica/Educador Físico);

✔️ Seguro de Vida em Grupo;

✔️ Gympass (pode incluir dependentes);

✔️ TotalPass;

## Range Salarial

A vaga paga entre R$ 5K - R$ 9K reais.

## Sobre a empresa

A G&P é uma das maiores integradoras de TI do mercado, possui soluções que dão o suporte necessário para cada estágio da Transformação Digital do seu negócio.
Atua há 31 anos no setor de Tecnologia da Informação e com o principal objetivo de ajudar nos desafios do seu negócio.
Presente nas principais capitais do Brasil, possuem uma equipe especializada trabalha para impulsionar a inovação necessária, garantindo que sua empresa prospere na era digital. Investem em um completo ecossistema de inovação para atender as principais verticais, oferecendo a tecnologia como solução aos clientes, com ofertas alinhadas às principais tendências de tecnologia.

## Como se candidatar

https://tally.so/r/w2KYEV

## Labels

- CLT
- Pleno
- Sênior

**Comment by joaofeliperl** [comment]
Não consigo anexar meu currículo, pois sempre é exibida uma mensagem de erro, fiz testes com arquivos menores e também não é possível.

**Comment by elzasimoes** [comment]
Enviado 🙏

**Comment by Delandiluca** [comment]
Tenho muito interesse!! Enviado currículo e candidatura... 🙌🏻🙏
