### ISSUE TITLE
[São Paulo] Analista de Qualidade de Software na C6 Bank

### ISSUE THREAD

**Issue by BelkissMM** [qa-brasil/vagas#116]
Requisitos
- Experiência anterior como Analista de Qualidade/Test Engineer/QA/ou qualquer papel relacionado.
- Familiaridade com framework de automação como Appium e Robot é um diferencial
- Conhecimento sobre diferentes tipos de teste automatizado: unitários, integrados, funcionais e end to end
- Conhecimento em conceitos relacionados a DevOps: Integração e Entrega Contínua, pipelines
- Familiaridade com leitura de logs
- Boas habilidades de resolução de problemas

UM BANCO CONSTRUÍDO DO ZERO

No C6 Bank acreditamos que a qualidade das nossas entregas é resultado de um esforço conjunto entre todas as pessoas envolvidas e você.

O C6 Bank nasce para ser um banco completo para pessoas físicas e jurídicas sem perder a agilidade e o espírito empreendedor de uma startup. Sem agências físicas, o C6 Bank oferece produtos financeiros acessíveis para todos os perfis de clientes.

Com sede em São Paulo, o grupo tem mais de 1.000 colaboradores. Menos de um ano após o lançamento, o C6 Bank já recebeu diversos prêmios. Fomos eleitos pelo site Glassdoor como empresa mais amada (2019), com base na opinião dos colaboradores, e ficamos em 2º lugar no LinkedIn Top Startups 2019, a lista das startups mais desejadas pelos brasileiros para se trabalhar. Além disso, a startup idwall elegeu o C6 Bank como o banco digital que tem o melhor processo de abertura de conta (2019).

O C6 Bank valoriza o diálogo, a abertura e, acima de tudo, o respeito. Estamos trabalhando para construir, em nosso dia a dia e nos nossos processos seletivos, uma cultura de respeito à diversidade. Aqui vale o poder do autor. Todo mundo deve ter liberdade e autonomia para propor novas ideias e construir coisas incríveis.

Queremos mudar a experiência das pessoas com os serviços financeiros. Quer participar dessa jornada com a gente? Confira nossas vagas e cadastre seu currículo no nosso banco de talentos!

Conheça mais sobre nós
https://www.linkedin.com/jobs/view/1997751628/

**Comment by JeffersonBru** [comment]
Remoto, presencial?

**Comment by BelkissMM** [comment]
Olá, entre em contato com a C6 Bank para saber mais detalhes. Eu apenas publiquei.
