### ISSUE TITLE
[Remoto] Tester na Troupe Tecnologia

### ISSUE THREAD

**Issue by victor-pilotto** [qa-brasil/vagas#1168]
## Descrição da vaga

 - Trabalhar com testes manuais;
 - Reportar bugs e melhorias;
 
## Local

 - Remoto;
 
## Horário de trabalho

 - Segunda a Quinta das 8h às 17:15 e Sexta das 8h às 16h;
 
## Benefícios

 - Vale alimentação;
 - Plano médico e odontológico;
 - Auxilio home office;
 - Horário dedicado ao estudo durante expediente;

## Requisitos

**Obrigatórios:**

 - Ter conhecimento em logica;
 - Ter conhecimento em SQL;

**Diferenciais:**

 - Ter conhecimento em testes automatizados com Cypress;
 - Ter conhecimento em Testlink;
 - Ter conhecimento em Jira;

## Contratação

 - CLT

## Nossa empresa

Uma empresa forte e moderna. Pronta para os grandes desafios!
A Troupe Brasil é reconhecida pela sua capacidade de entregar soluções para problemas dos mais diversos portes. Já são 30 anos oferecendo ao mercado o que há de melhor, sempre trabalhando com foco na viabilidade e retorno ao seu cliente.
Pelo Brasil e pelo mundo, a Troupe tem deixado o legado de grandes parcerias e bons relacionamentos, acumulando testemunhos positivos que lhe garantem seguir investindo para se manter como uma das principais empresas de seu setor.

## Como se candidatar

Por favor envie um email para victor.tecnologia@troupebrasil.com.br com o seu CV anexado
Enviar no assunto: **Vaga Tester** e com a pretensão salarial, se possível

**Comment by Delandiluca** [comment]
Enviado o currículo!!
