### ISSUE TITLE
[Rio de Janeiro] Product Owner na Ceptis

### ISSUE THREAD

**Issue by BelkissMM** [qa-brasil/vagas#117]
Principais Atividades e Responsabilidades:

- Colaborar com a equipe de Soluções para traduzir os requisitos de negócios em user stories para as equipes de desenvolvimento implementarem;
- Fornecer orientação e remover obstáculos para garantir a execução bem-sucedida de projetos usando a metodologia Scrum;
- Liderar a resolução de problemas e a melhoria contínua da solução, identificando as principais partes interessadas, e motivando grupos de trabalho para melhorar tópicos específicos;
- Trabalhar com as equipes de desenvolvimento para garantir que elas entendam a visão do produto ou projeto, e estejam fornecendo recursos robustos e reutilizáveis;
- Desenvolver especificações detalhadas de produtos ou projetos, de forma que sejam claramente entendidas pelas equipes de desenvolvimento;
- Participar da elaboração dos critérios de aceitação das user stories e fornecer exemplos de apoio no desenvolvimento orientado a testes de aceitação (ATDD);
- Trabalhar com outros product owners para identificar lacunas e sobreposições de recursos, a fim de garantir alta capacidade de reutilização entre projetos e produtos;
- Gerenciar a documentação interna de produto / projeto;
- Liderar reuniões de planejamento de sprint;
- Ser a maior fonte de informações sobre as prioridades do projeto;
- Indicar os itens necessários do produto e do backlog de projeto;
- Garantir que as entregas do Projeto sejam visíveis, claras e transparentes para todos.

Perfil:

- Graduação em Engenharia, Ciências da Computação ou áreas correlatas;​​
- Pós Graduação em Gestão de Projetos será diferencial;
- Inglês (Intermediário / Avançado);
- Sólida experiência em desenvolvimento de produtos e/ou projetos;
- Familiaridade com as ferramentas Confluence, JIRA, Bitbucket, Bamboo;
- Conhecimento em Metodologia Ágil, principalmente Scrum e Kanban;
- Certificação Agile e PMP será diferencial.

Local de trabalho: Santa Cruz/RJ

Tipo de contratação: CLT
Benefícios oferecidos pela CEPTIS:
- Ônibus executivo para o transporte dos funcionários;
- Vale Transporte;
- Gratificação;
- Investimento em cursos, treinamentos e certificações;
- Café da manhã e almoço (Servidos em refeitório interno);
- Lanchonete;
- Plano de saúde e odontológico (Funcionário e dependentes legais);
- Previdência Privada;
- Seguro de Vida;
- Área de Convivência (Totó, vídeo games, tênis de mesa, jogos de tabuleiro, sinuca, área de TV, área de leitura);
- Espaço para práticas de meditação MindFulness;
- Day Off (Folga a cada dois meses definido em calendário anual);
- Day Off (Folga no mês do seu aniversário);
- Quartas-feiras um ônibus circular para o shopping e centro de Itaguaí;
- Posto médico;
- Ações e Eventos de integração e conhecimento;
- Ambiente acolhedor e colaborativo.

Você conhece a Ceptis?

A Ceptis tem a vocação para desenvolver parcerias na exploração de soluções inovadoras, com o uso de tecnologia de ponta, especialmente na implantação de sistemas de rastreamento com marcação segura. Baseada em tintas de segurança visíveis e invisíveis, a utilização pode ocorrer no controle de produção industrial, da garantia de autenticidade, origem de produtos agrícolas, confiabilidade de medicamentos, marcação de combustível, entre outros. 
Somos uma empresa nova, ágil e moderna. Prezamos por um ambiente de muita colaboração e cooperação.

Acesse o material abaixo. 
https://ceptis.com.br/br/ 
https://www.linkedin.com/company/ceptis/?originalSubdomain=pt 
https://www.youtube.com/watch?v=kL7fjwHzl7s 
https://www.youtube.com/watch?v=nLi9TVSoJmU

**Comment by PauloGoncalvesBH** [comment]
Olá @BelkissMM, esse repositório é apenas para vagas de QA. Para vagas de outros tipos verifique a seção ['Outros repositórios de vagas'](https://github.com/qa-brasil/vagas#outros-reposit%C3%B3rios-de-vagas).
Ao divulgar no repositório relacionado à vaga mais candidatos irão aparecer.
