### ISSUE TITLE
[Rio de Janeiro] Analista de Desenvolvimento Full Stack Jr na Ceptis

### ISSUE THREAD

**Issue by BelkissMM** [qa-brasil/vagas#118]
Principais Atividades e Responsabilidades:

- Desenvolver, testar e entregar aplicações multi-plataformas;
- Elaborar documentação técnica de acordo com as metodologias e processos da empresa;
- Utilizar as ferramentas para controlar os desenvolvimentos e atividades de acordo com a especificação da empresa;
- Analisar documentação para apoiar o desenvolvimento e a solução;
- Entregar soluções inovadoras atendendo as especificidades do cliente;
- Criar pacotes de módulos para reutilização e automatização de código;
- Trabalhar como extensão da equipe de desenvolvimento na padronização e otimização utilizando as melhores práticas de desenvolvimento.

Perfil:

- Graduação em Engenharia da Computação, Ciência da Computação, Tecnologia da Informação ou área correlatas;
- Indispensável Inglês Intermediário;
- Desejável experiência em Java 8+;
- Desejável experiência em Java swing;
- Desejável experiência em banco de dados relacional;
- Conhecimento em algum framework web como: AngularJs, React, Vue, será considerado diferencial.

Local de trabalho: Santa Cruz/RJ

Tipo de contratação: CLT

Benefícios oferecidos pela CEPTIS:

- Ônibus executivo para o transporte dos funcionários;
- Vale Transporte;
- Gratificação;
- Investimento em cursos, treinamentos e certificações;
- Café da manhã e almoço (Servidos em refeitório interno);
- Lanchonete;
- Plano de saúde e odontológico (Funcionário e dependentes legais);
- Previdência Privada;
- Seguro de Vida;
- Área de Convivência (Totó, vídeo games, tênis de mesa, jogos de tabuleiro, sinuca, área de TV, área de leitura);
- Espaço para práticas de meditação MindFulness;
- Day Off (Folga a cada dois meses definido em calendário anual);
- Day Off (Folga no mês do seu aniversário);
- Quartas-feiras um ônibus circular para o shopping e centro de Itaguaí;
- Posto médico;
- Ações e Eventos de integração e conhecimento;
- Ambiente acolhedor e colaborativo.

Você conhece a Ceptis?

A Ceptis tem a vocação para desenvolver parcerias na exploração de soluções inovadoras, com o uso de tecnologia de ponta, especialmente na implantação de sistemas de rastreamento com marcação segura. Baseada em tintas de segurança visíveis e invisíveis, a utilização pode ocorrer no controle de produção industrial, da garantia de autenticidade, origem de produtos agrícolas, confiabilidade de medicamentos, marcação de combustível, entre outros. 

Somos uma empresa nova, ágil e moderna. Prezamos por um ambiente de muita colaboração e cooperação.

Acesse o material abaixo. 
https://ceptis.com.br/br/ 
https://www.linkedin.com/company/ceptis/?originalSubdomain=pt 
https://www.youtube.com/watch?v=kL7fjwHzl7s 
https://www.youtube.com/watch?v=nLi9TVSoJmU

**Comment by PauloGoncalvesBH** [comment]
Olá @BelkissMM, esse repositório é apenas para vagas de QA. Para vagas de outros tipos verifique a seção ['Outros repositórios de vagas'](https://github.com/qa-brasil/vagas#outros-reposit%C3%B3rios-de-vagas).
Ao divulgar no repositório relacionado à vaga mais candidatos irão aparecer.
