### ISSUE TITLE
[Rio de Janeiro] Analista de Desenvolvimento - iOS na Ceptis

### ISSUE THREAD

**Issue by BelkissMM** [qa-brasil/vagas#119]
Principais Atividades e Responsabilidades:
• Projetar, desenvolver, testar e entregar aplicações iOS nativas;
• Participar do ciclo de desenvolvimento de aplicações, da fase inicial à entrega e fase de manutenção;
• Foco no desenvolvimento de aplicações iOS e a integração dessas aplicações com serviços back-end;
• Estar profundamente envolvido nos princípios da arquitetura de aplicativos móveis, sendo capaz de criar fluxos de processos, wireframese modelos visuais;
• Elaborar a documentação de todo o desenvolvimento de acordo com a metodologia da empresa;
• Usar ferramentas para controlar o desenvolvimento de acordo com as especificações da companhia;
• Analisar documentação para apoiar o processo de desenvolvimento da solução;
• Entregar soluções específicas e inovadoras de acordo com as necessidades do cliente;
• Aplicar práticas de teste de última geração em nível unitário e de integração;
• Criar módulos de software que permitam implementação automática;
• Trabalhar com times de desenvolvimento amplos e com as melhores práticas de desenvolvimento padronizado e otimizado.

 

 Perfil:
• Graduação em Engenharia da Computação, Ciências da Computação, Tecnologia da Informação ou área correlata;
• Experiência em desenvolvimento de aplicações iOS;
• Inglês intermediário / avançado é indispensável;
• Espanhol / Francês serão considerados diferenciais;
• Profundo conhecimento nas linguagens Objective-C ou Swift e CocoaTouch;
• Experiência em frameworks iOS tais como Core Data, Core Animatione etc;
• Experiência com armazenamento offline, segmentação e ajuste de desempenho;
• Familiaridade com RESTfulAPIs para conectar aplicações iOS aos serviços de back-end;
• Conhecimento em princípios de arquitetura e design Apple e diretrizes de interface;
• Conhecimento em bibliotecas low-levelC-basedé um diferencial;
• Ter ao menos um app iOS original publicado (ou ao menos um app pessoal em um repositório público tal como GitHub) será considerado diferencial;
• Familiaridade com JIRA, Confluence, Bitbucket, Jenkins;
• Familiaridade com banco de dados relacional;
• Conhecimento em metodologia de desenvolvimento ágil.

Quer nos conhecer melhor? Acesse o material abaixo. 
https://ceptis.com.br/br/ 
https://www.linkedin.com/company/ceptis/?originalSubdomain=pt 
https://www.youtube.com/watch?v=kL7fjwHzl7s 
https://www.youtube.com/watch?v=nLi9TVSoJmU

**Comment by PauloGoncalvesBH** [comment]
Olá @BelkissMM, esse repositório é apenas para vagas de QA. Para vagas de outros tipos verifique a seção ['Outros repositórios de vagas'](https://github.com/qa-brasil/vagas#outros-reposit%C3%B3rios-de-vagas).
Ao divulgar no repositório relacionado à vaga mais candidatos irão aparecer.
