### ISSUE TITLE
[Recife] QA no CESAR

### ISSUE THREAD

**Issue by mahtejo** [qa-brasil/vagas#13]
## Descrição da vaga

Se você curte atuar com testes, sabe como desenhar casos de testes, costuma fazer o acompanhamento de bugs no dia a dia, já atuou em equipes multidisciplinares e é movido a desafios, a oportunidade de Eng. Testes Jr faz match contigo!

O que a pessoa atuando no cargo de Eng. Testes Jr faz?

Ela irá se relacionar bem com todos os membros da equipe e com os clientes para realizar discussões sobre os requisitos, pensar em qualidade como uma cultura e sempre estar disponível para conversar sobre os possíveis problemas e soluções dentro do escopo dos projetos e instituição.

## Local

Remoto ou Escritório, Recife - Recife Antigo

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 630/mês
- Auxílio creche
- Auxílio lente
- Auxílio aluguel
- Auxílio idioma

#### Diferenciais

- Sinuca
- No dress code
- Frigobar com cervejinha
- Aulas de exercício físico
- Ginástica Laboral

## Requisitos

**Obrigatórios:**
- Superior completo em Ciência da Computação, Engenharia da computação, Sistemas de Informação e áreas afins;
- Conhecimento intermediário no idioma inglês;
- Experiência na área de testes de software.
- Experiência em estratégias, planejamento e execução de cenários de testes em sistemas de informações, desenvolvimento de queries em SQL Server.
- Conhecimento básico em automação de testes;
- Estar confortável com ambientes de desenvolvimento ágeis;

**Desejáveis:**

**Diferenciais:**
- Conhecimento avançado no idioma inglês;
- Conhecimento prático com OO para desenvolvimento e manutenção de testes automáticos;

## Contratação

CLT Full

## Nossa empresa

O CESAR é um centro privado sem fins lucrativos, às vezes descentralizado, que acredita na inovação para transformar as vidas de pessoas e organizações. Enxergamos software em tudo e, através dele, a solução de problemas complexos nas mais diversas áreas de atuação. Em resumo: a gente é massa e respira inovação!

## Como se candidatar

https://vagas.cesar.org.br/p/38c3e119470d-engenheira-o-de-testes-j-nior
https://vagas.cesar.org.br/p/c7a5aee90fc6-engenheira-o-de-testes-s-nior
https://vagas.cesar.org.br/p/ee3cf7842b2c-engenheira-o-de-testes-pleno

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- Alocado
- CLT
- Júnior
- Pleno
- Remoto
- Sênior

**Comment by Daniray2008** [comment]
Olá, a vaga Inda está disponível?

**Comment by PauloGoncalvesBH** [comment]
@Daniray2008 Dos 3 links postados (júnior, pleno e sênior), o de sênior ainda está ativo.
Se te interessar, candidata lá: https://vagas.cesar.org.br/p/c7a5aee90fc6-engenheira-o-de-testes-s-nior
