### ISSUE TITLE
[Curitiba-PR]  GO ON ASSOCIATED

### ISSUE THREAD

**Issue by GOONASSOCIATE** [qa-brasil/vagas#152]
Desenvolvedor FULL STACK

## Local de trabalho

durante a pandemia remoto e pós pandemia presencial no escritório em Curitiba - PR, Água Verde

## Requisitos da vaga

**Obrigatórios**
- Sólida experiência com JavaScript, HTML, CSS
- Experiência em pelo menos um Framework atual, como Angular, Ember, React.
- Experiência em modelagem e arquitetura front-end, integrações utilizando API REST.
- Experiência em controle de versão, preferencialmente Git e uso do GitHub.
- Conhecimentos em React/Vue, Flux, bundlers e transpilers.
- Experiência com desenvolvimento Java, Android.
- Ambientes AWS, Google Cloud  

## Forma de contratação

PJ 

## Sobre a empresa
A Go On Associated oferece softwares de gestão empresarial e soluções tecnológicas diferenciadas para os setores de Construção, Manufatura, Combustíveis, Agronegócios e Serviços.

## Como se candidatar

- Por favor envie um email para vagas@gocn.com.br com seu CV anexado - Enviar no assunto: Vaga Desenvolvedor Full STACK

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

E-mail para contato em caso de não haver resposta: vagas@gocn.com.br

## Labels

- PJ
- Pleno
- Sênior
- Especialista
- Presencial
- Remoto
- Curitiba

**Comment by PauloGoncalvesBH** [comment]
@GOONASSOCIATE esse repositório é apenas para vagas de QAs. Procure o repositório que te atende no [README do repositório](https://github.com/qa-brasil/vagas#outros-reposit%C3%B3rios-de-vagas) e divulgue na mesma.
Vou fechar a task por esse motivo.
