### ISSUE TITLE
[Curitiba] Desenvolvedor FullStack Javascript [GO ON ASSOCIATED]

### ISSUE THREAD

**Issue by GOONASSOCIATE** [qa-brasil/vagas#153]
## Local de trabalho
Durante a pandemia remoto e pós-pandemia presencial no escritório em Curitiba - PR, Água Verde

## Requisitos da vaga

- Sólida experiência com JavaScript, HTML, CSS.
- Experiência em pelo menos um framework atual, como Angular, Ember, React.
- Experiência em modelagem e arquitetura front-end, integrações utilizando API REST.
- Experiência em controle de Versão preferencialmente Git e uso do GithHub.
- Conhecimento em React/Vue, Flux, Bundlers e transpilers.
- Experiência com desenvolvimento Java, Android.
- Ambiente AWS, Google cloud 

## Forma de contratação

PJ 

## Sobre a empresa

A Go On Associated oferece softwares de gestão empresarial e soluções tecnológicas diferenciadas para os setores de Construção, Manufatura, Combustíveis, Agronegócios e Serviços.

## Como se candidatar

- Por favor envie um e-mail para vagas@gocn.com.br com seu CV anexado - Enviar no assunto: Vaga Full Stack
- Candidatar através do site xyz

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels
- PJ
- Pleno
- Sênior
- Especialista
- Presencial
- Remoto
- Paraná

**Comment by PauloGoncalvesBH** [comment]
@GOONASSOCIATE esse repositório é apenas para vagas de QAs. Procure o repositório que te atende no [README do repositório (clique aqui)](https://github.com/qa-brasil/vagas#outros-reposit%C3%B3rios-de-vagas) e divulgue na mesma.
Vou fechar a task por esse motivo.
**Se persistir será impedido de postar mais issues no repositório.**
