### ISSUE TITLE
[Sāo Paulo] QA na BLU365

### ISSUE THREAD

**Issue by raphaguasta** [qa-brasil/vagas#17]
# Analista de Testes Jr

## A empresa:
Com a proposta de ajudar os brasileiros a negociarem suas dívidas e a se manterem no azul sempre, a BLU365 oferece uma plataforma de negociação fácil, intuitiva e digital, para seus clientes ficarem no azul o ano todo.

## O que você vai fazer:

- Escrever testes BDD/TDD em GWT contemplando regras de negócio
- Gerar massa de dados para testes
- Escrever robôs em Selenium para Q&A web
- Escrever crawlers de dados

## O que esperamos de você:
- Estudo e aprendizado constante
- Habilidade de evoluir por conta própria

## Requisitos:
- Noções de BDD e TDD
- Linguagem given-when-that
- Web services
- Programação Python
- XML, HTML, XPATH / Seletores CSS

Aqui você vai trabalhar com:
- Ambiente Linux
- Cloud/AWS
- Docker
- Scrappers
- Selenium
- Testes automatizados

## Onde estamos:
Estamos no Cubo Itaú, o maior centro de empreendedorismo tecnológico da América Latina!
Vila Olímpia - Sāo Paulo, SP

## Sobre a vaga:
- PJ
- Vale Transporte 
- Vale Refeiçāo
- Férias
- 13 salário
- Convenio médico
- Incentivo a cursos
- No Dress Code
- Horário flexível

## Aqui você também tem:
- Refeitório com microondas
- Pebolim, mesa de ping-pong, sinuca
- Chopp free a partir das 18:00hrs :)

**Cvs para: curriculos@blu365.com.br**

**Comment by webmassao** [comment]
Add

**Comment by PauloGoncalvesBH** [comment]
@raphaguasta Está faltando info de como se candidatar para a vaga.

**Comment by raphaguasta** [comment]
> @raphaguasta Está faltando info de como se candidatar para a vaga.

Ops!!! Cvs para: curriculos@blu365.com.br

Obrigado @PauloGoncalvesBH :)
