### ISSUE TITLE
[REMOTO] Quality Assurance na UP Outsourcing

### ISSUE THREAD

**Issue by giovanarezende** [qa-brasil/vagas#170]
## Descrição da vaga

Esta oportunidade visa o Teste de Qualidade na indústria de jogos na Europa. O inglês fluente é exigido para conversação com o time remoto.

Responsabilidades:
- Automação de Testes Utilizando Cypress
- Estar sempre atualizado sobre os padrões de Qualidade de Software
- Documentar os processos de Qualidade
- Experiência com metodologias Ágeis
- Colaboração diária com o Time de Desenvolvimento

## Local de trabalho

100% Remoto

## Requisitos da vaga

**Obrigatórios**
- Inglês Fluente
- Experiência com Cypress

## Forma de contratação

PJ 

## Benefícios da empresa

- Contrato PJ
- Aulas de Inglês Complementares (conversação)
- 10 dias de férias remuneradas
- 30 dias de férias não-remuneradas
- Produzir, modificar e otimizar aplicações web
- Horário Flexível
- Home Office
- Escritórios em Bauru/SP com estrutura completa
- Participação no lucros pago mensalmente
- Cursos/Treinamentos/Certificações
- Treinamentos e webinários regulares sobre saúde mental
- Folga sempre que precisar, com aviso antecipado

## Sobre a empresa

UP Outsourcing é uma empresa localizada em Bauru, no interior de São Paulo, a 326 km da capital com uma média de 379.000 habitantes.

Nós oferecemos oportunidades para desenvolvedores Web, baseado em Princípios de Desenvolvimento Ágil. Também auxiliamos Startups com Protótipos usando os Princípios de Inovação para a necessidade do cliente.

## Como se candidatar

Envie seu currículo para:  rh@upoutsourcing.com

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.

## Labels

- PJ
- Pleno
- Sênior
- Remoto
- Para todo o Brasil

**Comment by giovanarezende** [comment]
@ravanscafi esta vaga já foi fechada! Como faço para excluir?

**Comment by ravanscafi** [comment]
@giovanarezende eu só cuido do repositório de PHP. os outros não. pra fechar, geralmente é só clicar no botão de "Close issue" aqui embaixo
