### ISSUE TITLE
[Remoto] QA na SIC Colégio Santo Agostinho

### ISSUE THREAD

**Issue by wstarlley** [qa-brasil/vagas#186]
Olá candidato!

Somos da área de inovação da SIC, mantenedora dos Colégios Santo Agostinho.

Estamos desenvolvendo produtos EdTech e buscando alguém inovador, dedicado, atento a detalhes, disponível e comprometido para ampliar nosso time, vamos encarar esse desafio e trazer novas ideias!

**ATRIBUIÇÕES E REQUISITOS:**
Realizar o planejamento, controle, especificação e execução de testes de software, utilizando diversas técnicas.
Realizar modelagem e execução de casos de testes.
Executar testes manuais em interface web e mobile.
Ter uma boa comunicação com os pontos focais dos projetos.
Ter senso crítico e prezar pela qualidade do software

**CONHECIMENTOS NECESSÁRIOS:**
Ter conhecimento em técnicas de testes.
Ter conhecimento intermediário/avançado em Excel.

**SERÁ UM DIFERENCIAL SE VOCÊ TIVER:**
Conhecimento em Bancos de Dados não relacional.
Conhecimento em ferramentas de testes automatizados como Selenium, Cypress e similares.
Conhecimento em BDD (Behavior-driven development)
Conhecimento em ferramentas de teste de API (Ex.: postman).
Conhecimento em ferramentas de gestão de testes como Jira, Mantis, Testlink ou outros.

**FORMAÇÃO:** Ensino Superior em ciência da computação ou sistemas de Informação e/ou áreas afins.

## Forma de contratação
CLT

## Localidade

100% Remoto

## Benefícios da empresa
- Plano de saúde
- Plano odontológico 
- Seguro de vida 
- Vale alimentação

## Range Salarial

Vamos avaliar  o nível profissional e pretensão de cada candidato

## Como se candidatar

- Por favor envie um email para wallyson.starlley@sicbh.com.br com seu CV anexado - Enviar no assunto: Vaga do QA-SIC

**Comment by brunopulis** [comment]
Olá @wstarlley a vaga necessita de mais informações relacionadas a localidade, por exemplo: 

## Localidade 

- 100% Remoto
- Presencial, escritório em Belo Horizonte - MG, bairro XPTO
- Híbrido. X dias remoto e Y dias presencial no escritório em Belo Horizonte - MG, bairro XPTO

Recomendo dar uma olhada no [template que disponibilizamos](https://github.com/qa-brasil/vagas/issues/new?template=adicionar-nova-vaga.md&title=%5BCidade%5D+QA+na+NOME+DA+EMPRESA)

**Comment by wstarlley** [comment]
Olá Bruno,

Fiz a alteração. Agradeço o apoio!

**Comment by brunopulis** [comment]
> Olá Bruno,
> 
> Fiz a alteração. Agradeço o apoio!

Imagina eu que agradeço! Por divulgar essa oportunidade por aqui. ❤️
