### ISSUE TITLE
{] QA na NOME DA EMPRESA

### ISSUE THREAD

**Issue by isisRH** [qa-brasil/vagas#192]
## Descrição da vaga

Projeto bazinga em Selenium, etc.

## Local de trabalho

- 100% Remoto
- Presencial, escritório em Belo Horizonte - MG, bairro XPTO
- Híbrido. X dias remoto e Y dias presencial no escritório em Belo Horizonte - MG, bairro XPTO

## Requisitos da vaga

**Obrigatórios**
- X anos de experiência com testes automatizados
- X anos de experiência com JUnit

**Desejáveis**
- conhecimentos em testes unitários com Jest
- conhecimentos em cypress

**Diferenciais**
- projetos open source
- conhecimento em docker

## Forma de contratação

PJ ou CLT

## Benefícios da empresa

- Plano de saúde X
- Seguro de vida X
- VR de R$ X/dia
- Auxílio creche
- ...

**Diferenciais**

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Range Salarial

A vaga paga entre X.000,00 e X.000,00 reais.

## Sobre a empresa

Aqui na Corporação XPTO somos líderes em...

## Como se candidatar

- Por favor envie um email para email@email.com.br com seu CV anexado - Enviar no assunto: Vaga do QA-Brasil
- Candidatar através do site xyz

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.

E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

## Labels

- CLT
- PJ
- Freela
- Estágio
- Júnior
- Pleno
- Sênior
- Especialista

- Presencial
- Remoto

- Rio Grande do Sul

- Exterior

**Comment by gstvinf** [comment]
Mas ein?

**Comment by PauloGoncalvesBH** [comment]
Olá @isisRH. Issue fechada por ser apenas o template disponibilizado, e não a vaga. Caso precise de apoio na abertura de vaga pode contatar algum dos administradores no LinkedIn.
Paulo Gonçalves: https://www.linkedin.com/in/paulo-goncalves
Bruno Pulis: https://www.linkedin.com/in/pulis
