### ISSUE TITLE
[São Paulo] QA no Zé Delivery

### ISSUE THREAD

**Issue by fbellato** [qa-brasil/vagas#20]
## Descrição da vaga

Zé Delivery é o maior delivery de bebidas do Brasil atualmente e crescendo!

## Local

Vila Olimpia - SP

## Benefícios

- 13º e 14º salário
- VT + VR
- Plano de saúde + odontológico
- Outros benefícios serão citados ao longo do processo

## Benefícios
- Remuneração variável

## Requisitos

**Obrigatórios:**
- Avaliar funcionalidades, criar estratégia de desenvolvimento e execução testes automatizados para aplicações de Web e Mobile
- Experiência em tecnologias como Selenium, Appium
- Análise de bugs e tracking de problemas reportados
- Execução e desenvolvimento de testes manuais e automatizados
- Experiência com metodologias e ferramentas de QA
- B.S., M.S. ou PHD em Ciência da Computação/Engenharia ou algo equivalente

**Desejáveis:**
- Experiência em testes de carga com automatizações
- Experiência em testes de API, tanto manual quanto automatizado
- Experiência com desenvolvimento usando CI/CD (TravisCI, Jenkins…)
- Git, SQL
- RobotFramework
- Criação de frameworks de testes UI e API
- Experiência em testes cross-platform usando BrowserStack, SauceLabs, AWS Device Farm etc
- Experiência em teste em serviços que utilizam GraphQL
- Amazon Web Services

## Contratação

CLT + Beneficios

## Nossa empresa

Zé Delivery é um empresa dentro do braço de inovação da AmBev, chamada ZXVentures

## Como se candidatar

Candidate-se pela nossa vaga no Linkedin: https://www.linkedin.com/jobs/view/1655874265/

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dias após cada processo.

## Labels

- CLT
- Júnior
- Pleno
- Sênior

**Comment by devhttps** [comment]
Ainda esta contratando?
