### ISSUE TITLE
[Brasil] QA Sr. na Sympla

### ISSUE THREAD

**Issue by karemandrade** [qa-brasil/vagas#212]
## Descrição da vaga

Como membro da equipe de Produto, você irá trabalhar ao lado de desenvolvedores, designers e outros profissionais na criação de soluções para os nossos usuários e será responsável por manter e aumentar a qualidade do nosso novo produto, o Sympla Play!

Seus desafios serão:

    Elaborar e executar casos de teste para aplicações web;
    Executar testes de regressão;
    Automatizar novas features;
    Identificar e analisar bugs;
    Participar da criação de projetos de automação para novos serviços.

## Local de trabalho

- Presencial ou Remoto

## Requisitos da vaga
**Desejáveis**
Procuramos profissionais comprometidos com resultados, pessoas que buscam ser protagonistas de sua carreira e que queiram construir junto novos processos e contribuir para soluções inspiradoras. Além disso:
    Conhecimento em automação de testes;
    Conhecimento em BDD.

**Diferenciais**
    Conhecimento em Ruby;
    Capybara;
    Cucumber;
    Conhecimento em ferramentas de teste de API;
    CI/CD.

## Forma de contratação
CLT

## Benefícios da empresa

Neste momento estamos atuando no Regime Home Office, por isso os benefícios que dizem respeito a estrutura física serão desfrutados quando retornamos ao nosso super escritório, mas considere:

    Ambiente criativo, inovador e estimulante;
    No dress code (Venha como se sentir melhor, fechou?);
    GymPass é um benefício corporativo de atividade física, nele você tem acesso a diversas modalidades de atividades em várias academias;
    Plano de Saúde Sulamérica com cobertura Nacional na modalidade apartamento;
    Plano Odontológico;
    O momento da cegonha chegou? Nossas licenças são estendidas! Maternidade 6 meses e paternidade 20 dias;
    Auxílio creche para crianças de até 4 anos e 12 meses para mamães e papais;
    Acesso gratuito ao MyAcademy, plataforma de e-learning com acesso a + 40.000 cursos dos mais variados temas e parceiros;
    Café expresso, bebidas variadas, frutas e snacks a qualquer hora do dia;
    Happy Hour que acontece uma vez ao mês em comemoração aos aniversariantes;
    Trabalhar lado a lado de pessoas que são apaixonadas pelo que fazem, tendo a oportunidade de aprender diariamente e ampliar seus conhecimentos;
    40h semanais.
    Folga de um dia no mês do aniversário, que é a nossa maneira de presentear o funcionário;

## Sobre a empresa

Simplicidade é nosso nome e sobrenome. Somos a maior plataforma de venda de ingressos e gestão de eventos do Brasil e temos orgulho de ter tecnologia e design no nosso DNA.

Acreditamos em experiências acessíveis, agradáveis e inspiradoras, que simplifiquem a vida das pessoas. Para acompanhar o crescimento da Sympla estamos escalando nosso time e para isso buscamos pessoas incríveis!

Nosso time atua sempre com foco nos melhores resultados, construímos juntos, somos analíticos e pensamos em todo o contexto para entregar com qualidade a melhor experiência para nossos clientes, entendendo seus dilemas.

## Como se candidatar

- https://www.sympla.com.br/trabalhe-conosco-vaga?gh_jid=5029315002&gh_src=ddd629312us

## Labels

- CLT
- Sênior
- Especialista

- Presencial
- Remoto

**Comment by apolation** [comment]
O link está indisponível, já encerraram as candidaturas? Obrigado.
