### ISSUE TITLE
[Portugal] Automation Tester na Integer Consulting

### ISSUE THREAD

**Issue by Catia987** [qa-brasil/vagas#213]
A INTEGER, uma empresa de consultoria na área das tecnologias, com mais de uma década de presença no mercado português, está à procura de Automation Tester (m/f), com fortes habilidades de comunicação e sentido de responsabilidade e de trabalho em equipa.

Este pode ser o desafio perfeito para ti se tens:

Experiência profissional mínima de 2 ou 3 anos na área. 
Experiência nas frameworks de Automação de Testes: UFT, Robot Framework, Cucumber;
Experiência em automatização de casos de teste; 
Experiência em Testes de API e/ou Performance;
Fluência em inglês

Se tens o amazINg talent pretendido e queres fazer parte da equipa INTEGER, responde a este anúncio com o teu CV atualizado para catia.jorge@integer.pt

Participar neste projeto significa a integração numa empresa sólida em crescimento e numa equipa jovem e dinâmica. 
Para saber mais como protegemos a sua privacidade, consulte a nossa Política em www.integer.pt

**Comment by PauloGoncalvesBH** [comment]
@Catia987 essa vaga é para trabalhar em Portugal ou a pessoa pode trabalhar do Brasil remotamente para Portugal?
Essa informação vai auxiliar as pessoas que virem a vaga.

**Comment by Catia987** [comment]
> @Catia987 essa vaga é para trabalhar em Portugal ou a pessoa pode trabalhar do Brasil remotamente para Portugal?
> Essa informação vai auxiliar as pessoas que virem a vaga.

Olá Paulo,
Obrigada. A vaga é para trabalhar em Portugal.
