### ISSUE TITLE
[São Paulo] Software QA Engineer na idwall

### ISSUE THREAD

**Issue by sfrubio** [qa-brasil/vagas#22]
## Descrição da vaga

- Planejar e executar testes funcionais e de aceite (caixa-preta).
- Acompanhar a cobertura de testes unitários e de integração (caixa-branca).
- Contribuir com a validação de novas ferramentas de qualidade e teste a serem utilizadas pela área de Tecnologia.
- Criar e manter scripts de testes automatizados de regressão.
- Planejar, automatizar e executar testes de desempenho (carga e stress).
- Reportar defeitos encontrados e priorizá-los adequadamente.
- Publicar relatórios periódicos com os resultados das execuções de testes.
- Construir experimentos e códigos que outras pessoas possam entender, adotar e estender.
- Atuar juntamente aos envolvidos do projeto na elaboração de estratégias e cenários de teste.

## Local

Escritório, São Paulo - Região da Paulista, próximo ao metrô Consolação

## Benefícios

- Assistência médica
- Assistência odontológica
- Vale Refeição
- Vale Alimentação

#### Diferenciais
- Benefício de saúde mental (ZenKlub)
- Auxílio creche
- Gympass
- Frutas
- Massagem

## Requisitos
**Obrigatórios:**

- Experiência prévia com atividades voltadas a qualidade de software, como análise de documentação, planejamento e execução de testes exploratórios e automatizados.
- Experiência em atividades de testes em processos ágeis, tais como: Kanban, Scrum, etc.
- Conhecimentos básicos de programação e fundamentos de computação.
- Conhecimentos em pelo menos uma dessas linguagens: Java, Javascript ou Ruby.
- Conhecimento sobre versionamento de código (Git) utilizando GitHub, Gitlab ou BitBucket.
- Conhecimentos em pelo menos um dos frameworks de automação de testes.
- Conhecimento sobre o protocolo HTTP e sobre APIs REST.

**Diferenciais:**

- Experiência em testes de aplicações mobile: manual e automação.
- Experiência em integração de testes com ferramentas de Integração Contínua (Gitlab CI/CD, Jenkins, CircleCI).
- Conhecimento de bancos de dados relacionais (SQL) e não-relacionais (NoSQL).
- Possuir certificação CTFL (Certified Tester Foundation Level).

## Contratação

CTL a combinar

## Nossa empresa

**Relações de confiança para todos**

Construímos tecnologias para enriquecer interações humanas. Com isso, negócios podem ser mais seguros, rápidos, inovadores e inclusivos. Nós ajudamos empresas a validar a identidade de seus usuários digitalmente.

**Nós criamos confiança através de tecnologia**

Fraudes de identidade são um problema bilionário no Brasil e geram regras de compliance e regulamentação que impedem operações de negócios de escalarem facilmente mantendo a segurança e a experiência do usuário. Nossos produtos usam machine learning e outras soluções de ponta para fornecer aos nossos clientes a resposta para esses problemas da melhor maneira possível.

## Como se candidatar

Aplicar-se à vaga utilizando o link [https://apply.workable.com/idwall/j/833244C85B/](https://apply.workable.com/idwall/j/833244C85B/)

## Labels

- Alocado
- CLT
- Sênior
- Pleno

**Comment by RaulBatalha** [comment]
Olá,
A vaga me interessou!

Eng°. Raul Batalha



Enviado do meu smartphone Samsung Galaxy.



-------- Mensagem original --------
De : Sergio Francisco Rubio <notifications@github.com>
Data: 14/02/2020 3:20 PM (GMT-04:00)
Para: qa-brasil/vagas <vagas@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: [qa-brasil/vagas] [São Paulo] QA Pleno na idwall (#22)

Descrição da vaga

  *   Planejar e executar testes funcionais e de aceite (caixa-preta).
  *   Acompanhar a cobertura de testes unitários e de integração (caixa-branca).
  *   Contribuir com a validação de novas ferramentas de qualidade e teste a serem utilizadas pela área de Tecnologia.
  *   Criar e manter scripts de testes automatizados de regressão.
  *   Planejar, automatizar e executar testes de desempenho (carga e stress).
  *   Reportar defeitos encontrados e priorizá-los adequadamente.
  *   Publicar relatórios periódicos com os resultados das execuções de testes.
  *   Construir experimentos e códigos que outras pessoas possam entender, adotar e estender.
  *   Atuar juntamente aos envolvidos do projeto na elaboração de estratégias e cenários de teste.

Local

Escritório, São Paulo - Região da Paulista, próximo ao metrô Consolação

Benefícios

  *   Assistência médica
  *   Assistência odontológica
  *   Vale Refeição
  *   Vale Alimentação

Diferenciais

  *   Benefício de saúde mental (ZenKlub)
  *   Auxílio creche
  *   Gympass
  *   Frutas
  *   Massagem

Requisitos

Obrigatórios:

  *   Experiência prévia com atividades voltadas a qualidade de software, como análise de documentação, planejamento e execução de testes exploratórios e automatizados.
  *   Experiência em atividades de testes em processos ágeis, tais como: Kanban, Scrum, etc.
  *   Conhecimentos básicos de programação e fundamentos de computação.
  *   Conhecimentos em pelo menos uma dessas linguagens: Java, Javascript ou Ruby.
  *   Conhecimento sobre versionamento de código (Git) utilizando GitHub, Gitlab ou BitBucket.
  *   Conhecimentos em pelo menos um dos frameworks de automação de testes.
  *   Conhecimento sobre o protocolo HTTP e sobre APIs REST.

Diferenciais:

  *   Experiência em testes de aplicações mobile: manual e automação.
  *   Experiência em integração de testes com ferramentas de Integração Contínua (Gitlab CI/CD, Jenkins, CircleCI).
  *   Conhecimento de bancos de dados relacionais (SQL) e não-relacionais (NoSQL).
  *   Possuir certificação CTFL (Certified Tester Foundation Level).

Contratação

CTL a combinar

Nossa empresa

Relações de confiança para todos

Construímos tecnologias para enriquecer interações humanas. Com isso, negócios podem ser mais seguros, rápidos, inovadores e inclusivos. Nós ajudamos empresas a validar a identidade de seus usuários digitalmente.

Nós criamos confiança através de tecnologia

Fraudes de identidade são um problema bilionário no Brasil e geram regras de compliance e regulamentação que impedem operações de negócios de escalarem facilmente mantendo a segurança e a experiência do usuário. Nossos produtos usam machine learning e outras soluções de ponta para fornecer aos nossos clientes a resposta para esses problemas da melhor maneira possível.

Como se candidatar

Aplicar-se à vaga utilizando o link https://apply.workable.com/idwall/j/833244C85B/

Labels

  *   Alocado
  *   CLT
  *   Sênior

**Comment by PauloGoncalvesBH** [comment]
Raul, há um link no final da descrição da vaga aonde pode se candidatar.

**Comment by RaulBatalha** [comment]
Obrigado!



Enviado do meu smartphone Samsung Galaxy.



-------- Mensagem original --------
De : Paulo Gonçalves <notifications@github.com>
Data: 14/02/2020 6:21 PM (GMT-04:00)
Para: qa-brasil/vagas <vagas@noreply.github.com>
Cc: Raul Batalha <raul.batalha@hotmail.com>, Comment <comment@noreply.github.com>
Assunto: Re: [qa-brasil/vagas] [São Paulo] QA Pleno na idwall (#22)


Raul, há um link no final da descrição da vaga aonde pode se candidatar.
