### ISSUE TITLE
[Campinas] QA na Sofist

### ISSUE THREAD

**Issue by lihvasc** [qa-brasil/vagas#23]
**Descrição da vaga:**
Essa pessoa irá se juntar ao nosso time de QA, fazendo parte de um time de especialistas que atuam com Testes Humanos, Testes Automatizados, Testes de Carga e Stress.
Além de fazer parte de projetos de alto impacto que afetam a vida de muitas pessoas.
Trabalhar com parceiros incríveis! Será responsável por:
Automatizar testes em projetos de apps e sistemas WEB utilizando BDD, frameworks de automação web/mobile e nuvens de dispositivos.
Apoiar o desenvolvimento de features e APIs que simulem ações dos usuários para uso durante os testes automatizados e testes exploratórios manuais.
Ajudar na manutenção dos ambientes de testes de integração.

**Local**
Temos posições para atuação Remota, nosso escritório se localiza em Campinas/SP 
Av. Júlio Prestes, 470 - Taquaral, Campinas - SP

**Benefícios**
Vale Alimentação
Vale Refeição
Plano de saúde (Unimed)
Plano odontológico
Seguro de vida
PLR
Horário Flexível
Auxílio Creche
Licença Maternidade e Paternidade Estendida
Gympass

**Diferenciais**
Possibilidade de Home Office
Café da manhã na empresa, 
Lanches como frutas, pão de queijo, sorvete etc
Breja Day
Day Off's

**Pré requisitos:**
Ensino Superior na área de TI;
Experiência com testes automatizados;
Inglês intermediário. 

**Diferenciais:**
Experiência anterior em consultoria de TI
Experiência na área comercial

**Contratação**
CLT - remuneração a combinar

Nossa empresa
A **Sofist** (www.sofist.com.br), consultoria de TI ultra especializada em qualidade de software

Como se candidatar
Se você gostou da oportunidade e acredita que pode fazer a diferença junto de nosso time técnico, não deixe de nos contatar! Envie um email para oportunidades@sofist.com.br com título **QA Testes Automatizados**

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: livia.santos@sofist.com.br

**Labels**
Nível pleno e sênior
Disponibilidade para pontuais visitas ao cliente.

**Comment by PauloGoncalvesBH** [comment]
Boa tarde @lihvasc , a vaga não cumpre com o modelo proposto definido. Para a vaga ter validade no repositório precisamos que seja seguido o seguinte formato:

## Descrição da vaga

Projeto bazinga em Selenium, etc.

## Local

Remoto ou Escritório, Belo Horizonte - Pampulha

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com testes automatizados
- 2 anos de experiência com JUnit e BDD

**Desejáveis:**
- conhecimentos em selenium
- conhecimentos em capybara

**Diferenciais:**
- projetos opensource
- certificações ISTQB

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga de QA

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

## Labels

- Alocado
- CLT
- Estágio
- Freela
- Júnior
- PJ
- Pleno
- Remoto
- Sênior
