### ISSUE TITLE
[São Leopoldo/RS] QA na CWI Software

### ISSUE THREAD

**Issue by CWI-RH** [qa-brasil/vagas#25]
Projetos com automação em Selenium.

Local
Remoto ou escritório em São Leopoldo/RS

Benefícios
Plano de saúde;
VR (Varia localidade);

...
Diferenciais
Dojos internos;
Medium interno.
...
Requisitos:
- Experiência com elaboração e execução de cenários de testes
- Experiência/conhecimento em automação de testes
- BDD/TDD
- Vivência em projetos de desenvolvimento de software com metodologias ágeis
Diferenciais:
- Dinâmico, objetivo, motivador, comunicativo, responsável e colaborativo
- Ter inteligência emocional e autoestima para lidar em situações de trabalho sob pressão
- Autossuficiente
- Trabalhar orientado a metas e com experiência em times ágeis

Nossa empresa
Sobre a CWI
Desde 1991, a CWI Software entrega soluções nas mais diversas tecnologias. Oferecendo serviços de qualidade, metodologia eficaz e equipe técnica qualificada

Como se candidatar
Por favor envie um email para work@cwi.com.br com seu CV anexado - enviar no assunto: Vaga de QA ou candidata-se em nosso site: https://cwi.com.br/oportunidades/Analista-de-Testes-Automatizados 

Tempo médio de feedbacks
Fazemos primeiro a triagem dos currículos e após o primeiro contato com o candidato já combinamos uma data para o retorno do mesmo.
E-mail para contato em caso de não haver resposta: work@cwi.com.br

Labels

CLT
Pleno
Remoto

**Comment by PauloGoncalvesBH** [comment]
Boa tarde @CWI-RH,  a vaga não cumpre com o modelo proposto definido. Quanto mais informações possuir, mais pessoas com o perfil desejado irão candidatar.

Para a vaga ter validade no repositório precisamos que seja seguido o seguinte formato:

_Qualquer dúvida/dificuldade que possuir, pode nos contatar._

---

## Descrição da vaga

Projeto bazinga em Selenium, etc.

## Local

Remoto ou Escritório, Belo Horizonte - Pampulha

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com testes automatizados
- 2 anos de experiência com JUnit e BDD

**Desejáveis:**
- conhecimentos em selenium
- conhecimentos em capybara

**Diferenciais:**
- projetos opensource
- certificações ISTQB

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação ACME somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga de QA

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

## Labels

- Alocado
- CLT
- Estágio
- Freela
- Júnior
- PJ
- Pleno
- Remoto
- Sênior

**Comment by Daniray2008** [comment]
Olá vcs tem algum estagio ou oportunidade de qa jr?

**Comment by CWI-RH** [comment]
Boa tarde Danielli, tudo bem?

Neste momento não temos essa oportunidade, mas você pode acompanhar em nosso site https://cwi.com.br/oportunidades =)

Obrigado pelo interesse em fazer parte da CWI e qualquer dúvida estamos à disposição.

Abraços!
Recursos Humanos
+55 51 3081.3600  |  cwi.com.br
[cid:image007.png@01D567FC.296DF830]<https://cwi.com.br/>     [cid:image008.png@01D567FC.296DF830] <https://www.facebook.com/CWIsoftwareLtda/>  [cid:image009.png@01D567FC.296DF830] <https://www.instagram.com/cwisoftware/>  [cid:image010.png@01D567FC.296DF830] <https://www.linkedin.com/company/cwi-software/>  [cid:image011.png@01D567FC.296DF830] <https://www.glassdoor.com.br/Avalia%C3%A7%C3%B5es/CWI-Software-Avalia%C3%A7%C3%B5es-E489537.htm>  [cid:image012.png@01D567FC.296DF830] <https://twitter.com/cwisoftware>



De: Danielli Oliveira <notifications@github.com>
Enviada em: sexta-feira, 12 de junho de 2020 08:47
Para: qa-brasil/vagas <vagas@noreply.github.com>
Cc: Oportunidades CWI - RS <work@cwi.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [qa-brasil/vagas] [São Leopoldo/RS] QA na CWI Software (#25)


Olá vcs tem algum estagio ou oportunidade de qa jr?
