### ISSUE TITLE
Belo Horizonte/MG- Grupo Aterpa

### ISSUE THREAD

**Issue by FernandaRosa07** [qa-brasil/vagas#394]
## Analista de Suporte

 Belo Horizonte/MG
- Presencial, escritório em Belo Horizonte - MG, bairro Estoril

## Requisitos da vaga

- Administração e manutenção de infraestrutura de Tecnologia da Informação (Servidores, Switches, Roteadores, Firewall, VPN, Estações de trabalho, Links de comunicação, etc.);

- Administração de servidores Linux e Windows;

- Administração de sistemas de Virtualização (VMware);

- Suporte aos sistemas operacionais e aplicações de utilização da empresa (Pacote Office, SAP®, Totvs, Compor, etc.).

- Disponibilidade para viagens para as obras da empresa.

**Obrigatórios**
- Experiência na função; 
- Residir em Belo Horizonte ou região.

**Desejáveis**
- Pós graduação em administração de redes e servidores ou segurança da informação/Cyber Security. - Certificação COBIT (Control Objectives for Information and Related Technology) ou a ITIL (Information Technology Infrastructure Library).

- Por favor envie um email para rh.corporativo@aterpa.com.br com seu CV anexado - Enviar no assunto: Analista de Suporte
ou acesse o nosso banco de dados e cadastre o seu currículo: https://lnkd.in/egHntmz

**Comment by PauloGoncalvesBH** [comment]
@FernandaRosa07 é permitido apenas vaga de analista de testes nesse repositório.
