### ISSUE TITLE
[São Paulo] QA na FacilPay

### ISSUE THREAD

**Issue by ReMaia** [qa-brasil/vagas#401]
## Descrição da vaga
Executar testes manuais e automatizados (stress, carga, performance, caixa branca e preta, exploratório, regressão, usabilidade, etc.).
 Realizar a preparação de massa de dados de testes, levantamento de cenários e roteiro de testes. Documentar bugs, casos de teste e débitos técnicos. 
Trabalhar com equipes multifuncionais

## Local de trabalho

- 100% Remoto

## Requisitos da vaga

**Obrigatórios**
Conhecimentos em frameworks de testes automatizados (Junit, Cypress, Selenium, Capybara, Cucumber, outros). 
Experiência em Docker, GIT e Jenkins. 
Experiência em montar ambientes de testes

**Desejáveis**
Necessário conhecer BDD (Behavior Driven Design), DDD (Domain Driven Design) e TDD (Test Driven Design), assim como ferramentas de análise estática, segurança, automação, performance e carga.

**Diferenciais**
Certificações voltadas para a área de QA como CTFL e CTAL
Ter atuado em projetos de meios de pagamentos

## Forma de contratação

PJ ou CLT

## Benefícios da empresa

- Seguro Saúde (Allianz)
- Seguro de vida 
- VR de R$ 32/dia
- Assistência odontológica

## Sobre a empresa
A Facilpay é uma fintech de meios de pagamento que está crescendo em ritmo acelerado e busca pessoas que queiram participar do desafio de estruturar a área e participar das decisões de tecnologia, com muita troca e aprendizado.

## Como se candidatar

- Faça sua inscrição no link: https://experht.pandape.com.br/Detail/84326. 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.

## Labels

- CLT
- PJ
- Pleno
- Sênior
- Remoto
- São Paulo

**Comment by santosvini** [comment]
A vaga no link disponibilizado, não está mais disponível para inscrição
Seria ideal fechar esta issue
