### ISSUE TITLE
[Home office] QA na alt.bank

### ISSUE THREAD

**Issue by SchultzVinicius** [qa-brasil/vagas#415]
## Descrição da vaga

Projeto QA Automation Mobile.

RESPONSABILIDADES E ATRIBUIÇÕES

- Participar do planejamento, elaboração e execução de testes automatizados e funcionais tanto para as aplicações quanto para os serviços;
- Realizar análises das entregas, criando os cenários de testes bem como participando das cerimônias dos times para identificar as necessidades;
- Levantamento de cenários de testes funcionais e não funcionais;
- Execução de testes manuais e automatizados, testes exploratórios, teste de regressão, teste de requisitos de funcionalidade cruzada;
- Identificar e atuar nos impactos do projeto e/ou histórias que afetem o time, o produto ou a organização;
- Quando necessário, levantar riscos e atuar na mitigação, aceite ou resolução dos mesmos;
- Acompanhar o time na entrega das histórias desde o comprometimento da atividade até entrega em produção;
- Atuar junto ao Product Owner (PO) e outras áreas de negócio na definição e priorização de backlog dos produtos
- Acompanhar chamados de sustentação do produto e atuar em melhorias para mitigação de problemas em produção

## Local de trabalho

- 100% Remoto

## Requisitos da vaga

**Obrigatórios**
- Conhecimentos sólidos em Qualidade de Software;
- Conhecimentos em metodologia Ágil;
- Conhecimentos de testes em multiplataformas, criação e execução de testes automatizados para Mobile;
- Conhecimento em versionamento de código (Git).
- Atuação com automação de testes e frameworks.
- Estruturação de projeto usando Page Object;
- Experiência com Appium.

## Forma de contratação

PJ 

## Benefícios da empresa

- Ambiente inclusivo e aberto a sugestões;
- Plano Gympass corporativo;
- 30 dias de descanso remunerado após 1 ano;
- Reembolso de plano de saúde;
- Desconto de até 30% nas mensalidades das principais universidades, como FGV, FIA e FIAP;
- Assinatura Alura.
**Diferenciais**

- Caso for de São Paulo ou de São Carlos, pode ir trabalhar no escritório, se for do interesse.
## Range Salarial

A vaga paga entre 5.000,00 e 9.000,00 reais.

## Sobre a empresa

Nascemos como uma plataforma que revoluciona o setor bancário brasileiro, porque, pela primeira vez, a comunidade pode ganhar comissões em vez de apenas pagar taxas. Forneceremos estrutura para que qualquer pessoa ou estabelecimento comercial possa oferecer serviços bancários.

Não queremos ser apenas uma conta bancária. Queremos ajudá-lo a manter o dinheiro de cada membro seguro, usá-lo melhor, acompanhar seus gastos, economizar dinheiro e, assim, fazer planos, realizar seus sonhos, construir coisas, estar preparado para o futuro.

Queremos fornecer as ferramentas certas, de forma justa e segura, para que os membros possam usar seu dinheiro, cuidar de sua família, assumir o controle financeiro de sua vida e ser ele o próprio banco.

Lançado em outubro de 2018 por meio de parcerias com o Banco Central do Brasil e Visa, a meta do alt.bank é reunir 30 milhões de brasileiros e 60 milhões de latino-americanos como membros por meio de uma taxa de crescimento que supera qualquer antecessor. Com sede em São Paulo, o alt.bank está expandindo rapidamente sua plataforma e construindo sua equipe principal.

Como pessoa desenvolvedora Analista em QA esperamos que acompanhe o time na entrega das histórias desde o comprometimento da atividade até entrega em produção. Atue junto ao Product Owner (PO) e outras áreas de negócio na definição e priorização de backlog dos produtos. Acompanhe chamados de sustentação do produto e atuar em melhorias para mitigação de problemas em produção

## Como se candidatar

- Candidatar através da vaga https://altbank.gupy.io/job/eyJqb2JJZCI6MTAyMDAzMSwic291cmNlIjoiZ3VweV9wdWJsaWNfcGFnZSJ9?jobBoardSource=gupy_public_page

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 05 dias após cada etapa.

E-mail para contato em caso de não haver resposta: vinicius.silva@altbank.co

## Labels

- PJ
- Sênior
- Especialista

**Comment by SchultzVinicius** [comment]
Ainda buscando

**Comment by GQUINHONERO** [comment]
Sim

Em qua., 4 de ago. de 2021 às 13:49, SchultzVinicius <
***@***.***> escreveu:

**Comment by SchultzVinicius** [comment]
Vaga Finalizada
