### ISSUE TITLE
[São Paulo] QA na Cognizant

### ISSUE THREAD

**Issue by tathifreixo** [qa-brasil/vagas#42]
## Descrição da vaga

Buscamos pessoas, com potencial e com vontade de se desenvolver, para trabalhar em nossos clientes, como Analista de Testes de Automação (Web e Mobile).

## Local de trabalho

Escritório, São Paulo - SP

## Requisitos da vaga

Cursando TI ou áreas correlatas;   
Conhecimentos      / Experiência:      
Versonamento de código fonte: GIT, SVN e outros;    Bancos de Dados relacionais e não relacionais;    Ferramentas de gestão de testes – Jira, Mantis, Testlink e outros;      Testes de API;    Selenium, Appium, BDD, Cucumber, SilkTest e Similares;    Testes em multiplataformas: Mobile, Web e       Desktop;    Diferentes ferramentas de testes automatizados.

## Forma de contratação

PJ ou CLT

## Benefícios da empresa

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

**Diferenciais**

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Sobre a empresa

Aqui na Corporação XPTO somos líderes em...

## Como se candidatar

- Por favor envie um email para email@email.com.br com seu CV anexado - Enviar no assunto: Vaga do QA-Brasil
- Candidatar através do linkedin xxxx

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.

E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

## Labels

- Alocado
- Remoto
- CLT
- PJ
- Freela
- Estágio
- Júnior
- Pleno
- Sênior
- Especialista

- Rio Grande do Sul

**Comment by PauloGoncalvesBH** [comment]
Vaga fechada por ser duplicação da vaga https://github.com/qa-brasil/vagas/issues/43
