### ISSUE TITLE
[REMOTO] QA Analyst Jr na DEXTRA

### ISSUE THREAD

**Issue by Mariadafne** [qa-brasil/vagas#468]
## Descrição da vaga

Seja QA Automation Analyst Jr na Dextra! 💚 Aqui a gente se adapta, transforma e evolui. Tudo isso de forma ágil. Desenvolvemos soluções que fazem a diferença. Somos humanos, digitais, agentes de transformação. Temos coragem para criar e inovar, sempre comprometidos com as pessoas. Nossa cultura de valorização ao aprendizado gera um ambiente de colaboração e empatia que ultrapassa fronteiras: estamos espalhados pelo mundo, sempre conectados. A evolução é digital, mas a história é humana. Venha escrever seu nome nessa história.

## Local de trabalho

- 100% Remoto🖥

## Requisitos da vaga

**Obrigatórios**
**Para se juntar a nós, o que precisa saber ☺**

- Ser fera na execução de **teste Funcional e não Funcional; Manual; Regressão e Exploratório**, bem como **Testes Automatizados**.
- Experiência com **gerenciador de Bugs**; Gerenciador de Casos de Teste.
- Conhecimento em lógica de programação e comandos **SQL**;
- Ser uma pessoa colaborativa e gostar de trabalhar em equipe!

**Desejáveis**

- Autonomia e liberdade pra criar
- Pensar e fazer!

**Diferenciais**

- Inglês avançado, algumas das vagas são para projetos internacionais!
- Ter vivências em **projetos ágeis**.

## Forma de contratação

CLT

## Benefícios da empresa
**O que você encontra na Dextra:**

Horário Flexível
🤩Plano de Carreira
😍Plano de Saúde
😃Plano Odontológico
🧠Telavita | Plataforma de saúde mental e psicoterapia online
🏃‍♀️Gympass
🤸‍♀️Yoga
🥗Vale Alimentação
🥙Refeição
🚗Transporte|Deslocamento
🥫Combustível
🖥Auxílio Home Office
👶Auxílio Creche
👩‍🦽Auxílio Dependente PCD's
❤Seguro de Vida
💰Programa Participação de Lucros

**Diferenciais**

- Feedback 360°
- Mentoria 3.0
- Comitê de Mérito
- Estrutura Horizontal
- Treinamento de Soft Skills
- Guildas para compartilhar conhecimento
- Indicação Premiada

## Range Salarial

A vaga paga entre 4.700,00 e 5.500,00 reais.

## Sobre a empresa

A **Dextra** é TOP 5 das **Melhores Empresas para se Trabalhar - Great Place to Work®️** Nacional e de Tecnologia da Informação, 2020! Hoje, estamos 100% remoto e vamos continuar anywhere! Somos mais de 1.000 experts em desenvolvimento de produtos digitais, combinamos metodologias de design, desenvolvimento ágil e novas tecnologias para transformar negócios. Somos agentes de transformação. 

## Como se candidatar

Para se candidatar e/ou saber mais sobre a vaga, clique nesse link: **https://bit.ly/3ntiCLb**

## Labels
- CLT
- Júnior
- Remoto

**Comment by Gui-Dias-Ferreira** [comment]
O link para se candidatar https://bit.ly/3ntiCLb está redirecionando para uma página que não existe.
