### ISSUE TITLE
[Belo Horizonte] QA na Sympla

### ISSUE THREAD

**Issue by rh-sympla** [qa-brasil/vagas#5]
## Quem somos?
Simplicidade é nosso nome e sobrenome. Somos a maior plataforma de venda de ingressos e gestão de eventos do Brasil e temos orgulho de ter tecnologia e design no nosso DNA. Acreditamos em experiências acessíveis, agradáveis e inspiradoras, que simplifiquem a vida das pessoas. Para acompanhar o crescimento da Sympla estamos escalando nosso time de Produto e Desenvolvimento e para isso buscamos pessoas incríveis!
Nosso time atua sempre com foco nos melhores resultados, construímos juntos, somos analíticos e pensamos em todo o contexto para entregar com qualidade a melhor experiência para nossos clientes, entendendo seus dilemas. 

 ## Porque o(a) Analista de Testes é importante para nós?

 Como membro do time de Produto e Desenvolvimento, você atuará com foco na Gestão da Qualidade, e será responsável pelo planejamento e execução dos testes, análise e identificação de erros em novas features, testar e monitorar funcionalidades e processos já existentes, identificando erros, suas possíveis causas raízes e reportando para as áreas responsáveis.

 ##  Seus desafios serão:

Planejamento de testes (criação de planos e casos de testes);
Executar testes manuais (testes funcionais, regressão, exploratório, dispositivos móveis, etc);
Monitorar novas features;
Identificar e registrar erros encontrados;
Apoiar na identificação das causas raízes para os erros levantados;
Criar relatórios gerenciais sobre os testes realizados e a qualidade do produto.
 
## Oferecemos:

Ambiente criativo, inovador e estimulante;
Regime de contratação CLT;
Salário compatível com o mercado, VT e VR;
Plano de Saúde e Odontológico;
Gympass;
No dress code (pode trabalhar de bermuda, chinelo, etc);
Clima descontraído;
Café, bebidas variadas e snacks.
Horário flexível :)
40h semanais, de segunda a sexta.  

## O que buscamos?

Procuramos pessoas que buscam ser protagonistas de sua carreira e que queiram construir junto novos processos e contribuir para soluções inspiradoras. Além disso:

Ampla experiência em testes funcionais;
Excelente capacidade analítica e habilidade de resolução de problemas;
Excelente capacidade de aprendizado;
Ser detalhista e proativo;
Conhecer os conceitos de startup;
Must rock!

## Alguns diferenciais para a função:

Conhecimento em testes automatizados;
Estar por dentro das tendências do mercado de e-commerce;
Conhecer sobre desenvolvimento de produto;
Cursos específicos sobre Gestão de Processos e Qualidade.
 
Valorizamos trabalhar em um ambiente de pluralidade e de inclusão, por isso todas nossas vagas também são para profissionais com deficiência.

 Se o seu perfil corresponde ao que acreditamos, venha fazer parte do nosso time!!!

## Inscrição:

https://www.sympla.com.br/trabalhe-conosco-vaga?gh_jid=4457284002

**Comment by brunopulis** [comment]
@rh-sympla bom dia a vaga deve seguir o padrão especificado incluído na abertura da issue.
