### ISSUE TITLE
[Porto Alegre / São Leopoldo] QA na CWI Software

### ISSUE THREAD

**Issue by CWI-RH** [qa-brasil/vagas#52]
## Analista de Testes Automatizados
O profissional de qualidade possui conhecimentos nas disciplinas de execução e análise de testes, tendo ainda alta capacidade técnica em programação. Apresenta uma característica inquieta e de buscar soluções automatizadas para evitar atividades repetitivas dentro das suas tarefas e da equipe.

## Local de trabalho
Porto Alegre e São Leopoldo. 

## Requisitos da vaga

**Obrigatórios**
- Experiência com elaboração e execução de cenários de testes. 
- Experiência em planejar estratégias de automação (funcional/performance/segurança).
- Experiência em estabelecer e manter as necessidades de acessos, massa de dados e configurações de ambientes, definir, criar e gerir arquiteturas e frameworks de testes automatizados.
- Experiência em codificar scripts de testes automatizados.

**Desejáveis**
- Conhecimentos em BDD/TDD, Cucumber, Selenium. 
- Conhecimentos em banco de dados. 

**Diferenciais**
- Boa capacidade analítica e investigativa.
- Vivência em projetos de desenvolvimento de software com metodologias ágeis.

## Forma de contratação
CLT

## Benefícios da empresa
- Plano de saúde
- Seguro de vida
- VR 
- Vale transporte

**Diferenciais**
- Dojos internos
- Medium 

## Sobre a empresa
Desde 1991, a CWI Software entrega soluções nas mais diversas tecnologias. Oferecendo serviços de qualidade, metodologia eficaz e equipe técnica qualificada. 

## Como se candidatar
- Por favor envie um email para  work@cwi.com.br com seu CV anexado - Enviar no assunto: Vaga do QA ou candidate-se em nosso site: https://cwi.com.br/oportunidades/Analista-de-Testes-Automatizados.

## Tempo médio de feedbacks
Fazemos primeiro a triagem dos currículos e após o primeiro contato com o candidato já combinamos uma data para o retorno do mesmo.
E-mail para contato em caso de não haver resposta: work@cwi.com.br

## Labels
- Alocado
- Remoto
- CLT
- Pleno
- Sênior
- Rio Grande do Sul

**Comment by doamaral** [comment]
Por que tem a Tag "Remoto"?
