### ISSUE TITLE
[Campinas-SP /São  Paulo/SP] QA automatizado na SOFIST

### ISSUE THREAD

**Issue by marianajesuss** [qa-brasil/vagas#54]
## Descrição da vaga

- Automatizar testes em projetos de apps Android e iOS e sistemas WEB utilizando BDD (Cucumber), Selenium Webdriver, Appium e nuvens de dispositivos
- Apoiar o desenvolvimento de features e APIs que simulem ações dos usuários para uso durante os testes automatizados e testes exploratórios manuais
- Ajudar na manutenção dos ambientes de testes de integração
- Auxiliar na capacitação de outros membros do time no processo e tecnologias usadas
- Propor ao time melhorias no processo que aprimorem o resultado que entregamos
- Introduzir ferramentas e metodologias que tornem o trabalho mais eficiente

## Local de trabalho

Campinas ou São Paulo (alocado no cliente) 
*estamos respeitando as orientações da OMS, devido ao COVID-19

## Requisitos da vaga

**Obrigatórios**

- Experiência com desenvolvimento de testes automatizados para sistemas Web
- Conhecimento em desenvolvimento de testes automatizados para apps Android e iOS
- Experiência no desenvolvimento de testes de aceitação
- Experiência com BDD (preferível com Cucumber)
- Capacidade de se autogerenciar na execução de tarefas
- Ser uma pessoa proativa, criativa e entusiasmada com o que faz
- Disponibilidade para eventuais viagens à região de São Paulo

**Diferenciais**

- Ter conhecimento em "Especificação por Exemplos"
- Ter conhecimento em Padrões de projeto
- Ter trabalhado em soluções usando banco de dados SQL e NoSQL
- Ter conhecimento em ferramentas de controle de versão (principalmente Git)
- Ter experiência com sistemas operacionais Linux/Unix
- Ter conhecimento em desenvolvimento mobile (iOS ou Android)
- Ter experiência com Docker
- Ter experiência com Java, Javascript, Ruby ou Python
- Ter conhecimento em Testes de unidade, Testes de Integração, Testes de Contrato, Testes de Performance

## Forma de contratação

CLT

## Benefícios da empresa

- Vale Refeição
- Vale Alimentação
- Plano de saúde (Unimed)
- Plano odontológico (Amil)
- Gympass
- Seguro de vida
- PLR
- Horário Flexível
- Auxílio Creche
- Licença Maternidade e Paternidade Estendida

**Diferenciais**

- Café da manhã na empresa
- Lanches
- Breja Day
- Day Off

## Sobre a empresa

Somos uma empresa que promove troca de conhecimento entre os colaboradores, entendemos que cada Sofistian@ tem uma habilidade que nos ajuda a crescer.  

Somos feitos por pessoas, por isso nossa prioridade é cuidar delas. Não é a toa que fomos, pela terceira vez consecutiva, certificados como um Great Place to Work. E foi com muito orgulho que conquistamos um espaço entre as 20 melhores empresa para trabalhar na nossa categoria, em 2019.

Aqui você encontrará um horário de trabalho flexível, day off de aniversário, café da manhã na empresa, não terá que se preocupar com dress code, e temos um ambiente que promove a diversidade, focado no respeito e colaboração.. Aliás, é com enorme orgulho que ressaltamos que em 2020 ficamos com nota 100 (máxima) no GPTW em itens como: as pessoas aqui são bem tratadas independentemente de sua orientação sexual, cor, etnia, sexo e idade. 

Isso só reforça nosso empenho e preocupação genuína com as pessoas.

Seja durante sua atuação remota ou no escritório físico, nosso clima organizacional é pautado em uma cultura de relações saudáveis, promovendo o desenvolvimento e a autonomia.

Trabalhando aqui você fará parte de um time que se ajuda e apoia, com liberdade para colocar suas ideias em prática, além de um programa de desenvolvimento apoiado por mentores técnicos, que são os melhores QA’s do mercado!

Se você ama o universo QA, você vai amar ser um(a) Sofistian@. Somos parceiros de grandes nomes do mercado de tecnologia, participamos de projetos incríveis, que vão te desafiar todos os dias a enriquecer seu conhecimento sobre o mundo de testes.

Vem pra Sofist!

## Como se candidatar

- Por favor envie um email para mariana.jesus@sofist.com.br com seu CV anexado - Enviar no assunto: QA Automatizado - via GitHub

## Labels
- Alocado
- Remoto
- CLT
- Pleno
- Sênior
- Especialista

- São Paulo

**Comment by Daniray2008** [comment]
Olá, gostaria de saber se vcs teriam uma oportunidade de qa jr ou estagio?

**Comment by marianajesuss** [comment]
Bom dia Danielli!
Tudo bem?

Obrigada pelo interesse na Sofist! :)

Infelizmente, por enquanto estamos com vagas somente para perfil pleno e
sênior :(

Mas ficarei muito feliz em ter o seu currículo e retomarmos contato assim
que abrir uma vaga jr, ou estágio! O que acha?

Atenciosamente,

--


*Mariana Jesus*Recursos Humanos

Tel: +55.19.3291.5321
mariana.jesus@sofist.com.br

[image: assinatura-gptw-stwc-nova.gif]
__________________________________
Sofist / One Day Testing
www.sofist.com.br
<http://s.bl-1.com/h/cJ7FqwXl?url=http://t.yesware.com/tt/f12f9cda193a008d118f7de0efd91ff9019b3836/2a04bb73c50fb168fbe8af36340f2b80/22856a4ba81f3b6864be9b4aa1ddf947/www.sofist.com.br>






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
