### ISSUE TITLE
[São Paulo] QA no Traders Club

### ISSUE THREAD

**Issue by TradersClub1** [qa-brasil/vagas#60]
O Traders Club "TC" é uma startup que está revolucionando o mercado financeiro brasileiro.
Com o propósito de democratizar o acesso à conteúdos sobre o mercado de investimentos,
criamos uma plataforma completa para atender traders de todos os níveis de conhecimento e
objetivos.

Estamos crescendo e buscando profissionais para garantir a qualidade das nossas aplicações web 
e mobile.

Presencial, São Paulo/SP, Vila Olímpia

O que irá fazer?

- Cenários, casos e execução de testes em plataforma web e mobile (IOS e Android):
- Scripts para automação
- Atuará em squad multidisciplinar, em metodologia ágil (Scrum).

Requisitos:

- Experiência com testes web e mobile
- Conhecimento básico e interesse em automação.

Desejável...

- Conhecimento em Jira.

Benefícios:
Plano de saúde
Vale Refeição
Bônus Anual

Diferenciais:

Jornada de trabalho flexível, com autonomia.
Ambiente informal, no dress code, espaço para descompressão, frutas e snacks à vontade.

Contratação
PJ

Candidatura:
Para candidatura, cadastre o seu currículo no link abaixo: https://jobs.solides.com/tradersclub/vaga/28301

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: juliana.morgado@tradersclub.com.br

## Labels
- PJ
- Pleno

**Comment by Daniray2008** [comment]
Olá vcs teriam uma oportunidade de estágio ou jr?

**Comment by leaovictor** [comment]
Olá tem alguma vaga de estágio ou Júnior?
