### ISSUE TITLE
[REMOTO] Analista de Testes na Tray

### ISSUE THREAD

**Issue by MoniquePaiva** [qa-brasil/vagas#649]
## Descrição da vaga
**Quem somos?**
Somos a Tray, a plataforma de e-commerce da Locaweb que transforma vidas, experiências e negócios por meio da tecnologia.

Com muito orgulho, fomos reconhecidos como a 31ª melhor empresa para se trabalhar no Brasil, entre as empresas de médio porte, segundo o Ranking GPTW. E não para por aí! No ramo de Tecnologia da Informação, somos a 29ª melhor empresa para se trabalhar no país; e isso significa que você veio ao lugar certo, não acha?

Dentre os nossos objetivos diários estão oferecer aos nossos colaboradores bem estar; ambiente colaborativo, diverso e inclusivo; trabalho em equipe, paixão pelo que fazemos e a possibilidade de se desenvolverem, para entregarmos aos clientes da Tray a melhor experiência e os melhores resultados de venda em e-commerce.

Atualmente, 100% dos nossos colaboradores  estão trabalhando de casa, pensando na saúde e na segurança de todos.

Nós respiramos, amamos e vivemos a tecnologia, e você? 

**Atribuições do Cargo:**
Construção e preparação de ambientes, massa de dados, script de testes, execução de caso de testes (manual e automatizada)
Reporte de bugs em issues trackers
Contribuir com a criação/manutenção de pipelines CI/CD

**E para tirar de letra, você precisa de:**
Conhecimento na área de qualidade e testes de Software
Especificação e modelagem de casos de teste
Teste de caixa preta, testes funcionais e não funcionais
Testes de integração, segurança e carga
Experiência em programação para Automação de Testes com ferramentas de automação
Capacidade de fazer sugestões de melhoria no processo de testes

**Conhecimentos em:**
RSpec
Cypress
Cucumber
APIs REST
Metodologias Ágeis 

## Local de trabalho

- 100% Remoto

## Forma de contratação
CLT

## Benefícios da empresa
Só quem é Tray tem:

Plano de Saúde Unimed 
Vale Refeição ou Vale Alimentação
Auxílio Creche
Programa de Participação de Lucros - PPR
Day Off no mês de aniversário
Seguro de Vida em Grupo
Plano Odontológico
Gympass
Licença maternidade de 6 meses
Horário flexível

## Como se candidatar

- Por favor envie um e-mail para com seu CV anexado - Enviar no assunto: Vaga do QA-Brasil
e/ou se candidatar através do site https://jobs.kenoby.com/locaweb/job/pessoa-analista-de-testes/61534a6d57d577536a767aac?utm_source=website

## Labels

- CLT
- Pleno
- Sênior
- Especialista

- Remoto

**Comment by Daniray2008** [comment]
Ola tenho uma duvida. A Vaga é apenas CLT ou PJ tambem? Pois na forma de contratação esta apenas CLT mas na Labels esta com o PJ. Eu tenho interesse na vaga se for PJ.
