### ISSUE TITLE
[Remoto] Estágio em QA na VipCommerce

### ISSUE THREAD

**Issue by gabrielhws** [qa-brasil/vagas#67]
## Descrição da vaga

Buscamos uma pessoa para estagiar focado em Quality Assurance na [VipCommerce](https://site.vipcommerce.com.br/). 

## Local de trabalho

100% Remoto

## Requisitos da vaga

- Perfil exploratório, comunicativo e autodidata
- Ser pró-ativo e interessado em aprendizado contínuo
- Ser engajado em pequenos times, clima de startup e negócios que crescem de maneira acelerada
- Cursando curso superior em Sistemas de Informação ou áreas similares
- Curiosidade sobre utilização de BDD

**Diferenciais**

- Conhecimentos em Cucumber ou Selenium ou Ghost Inspect
- Formação técnica é um plus

## Forma de contratação

Estágio

## Benefícios da empresa

- Bolsa estágio
- Home Office
- Boa flexibilidade de horários de trabalho

## Sobre a empresa

A VipCommerce nasceu dentro de um supermercado e com vários anos de experiência no segmento varejista, entendemos o dia-a-dia do setor. E, prevendo que a venda online seria um progresso natural para os supermercados, transformamos nosso conhecimento em uma solução completa e robusta para habilitar as lojas tradicionais a venderem online.

## Como se candidatar

- Candidatar-se em: [https://bit.ly/3gAZbcD](https://bit.ly/3gAZbcD)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 48 horas após cada etapa do processo.

E-mail para contato em caso de não haver resposta: contato@coodesh.com

## Labels
- Remoto
- Estágio
- Minas Gerais

**Comment by gabrielhws** [comment]
Em  análise das pessoas que aplicaram. 
32 pessoas. 
Próxima etapa: proca técnica.

**Comment by agsvensson** [comment]
Bahh... perdi essa! Quando vi já estava fechada :(
