### ISSUE TITLE
[Remoto] Test Engineer na Pagar.me

### ISSUE THREAD

**Issue by samycici** [qa-brasil/vagas#69]
## Descrição da vaga

Aqui você vai:
- Participar das diferentes fases dentro do desenvolvimento de software para acrescentar a visão de qualidade
- Compartilhar conhecimento sobre testes e boas práticas com os times de desenvolvimento
- Ter a visão de integração entre os sistemas
- Ajudar a definir guidelines de qualidade que ajudem os times nas entregas
- Trazer visibilidade da qualidade dos sistemas através de métricas
- Ajudar os times a definir a estratégia de teste adequada para cada tipo de projeto
- Se preocupar com a conformidade contínua com os requisitos de qualidade e regulamentares do setor
- Entender as necessidades dos nossos clientes e encaixá-las no processo de teste
- Analisar as tecnologias atuais usadas na empresa e desenvolver etapas e processos para melhorar os procedimentos de teste

## Local de trabalho

Remoto

## Requisitos da vaga

**Obrigatórios**
- Experiência anterior como Test Engineer/QA/ou qualquer papel relacionado
- Familiaridade com ferramentas de teste do mundo Javascript
- Conhecimento sobre diferentes tipos de teste automatizado: unitários, integrados, funcionais
- Conhecimento em conceitos relacionados a DevOps: Integração e Entrega Contínua, pipelines
- Boas habilidades de resolução de problemas

**Desejáveis**
- Familiaridade com leitura de logs e APM (Application Performance Monitoring)

**Diferenciais**
- Conhecimento em testes de contrato

## Forma de contratação

CLT

## Benefícios da empresa

- Plano de Saúde e Odontológico (sem co-participação)
- Vale Refeição e/ou Vale Alimentação.
- Seguro de Vida.
- Incentivo a idas a Eventos e Treinamentos.
- Gympass

## Sobre a empresa

O Pagar.me é uma empresa brasileira de tecnologia de pagamentos online que trabalha para descomplicar o dia a dia de quem empreende digital. Conectamos lojistas ao ecossistema de pagamentos com apenas uma integração, cuidando de toda a burocracia para que tenham mais tempo para focar no negócio.

## Como se candidatar

- Se inscrever pelo [site](https://pagarme.gupy.io/jobs/246112)

## Labels

- Remoto
- CLT
- Pleno
- Sênior

**Comment by JeffersonBru** [comment]
Link está com problema.

**Comment by renatodefarias** [comment]
Pelo que eu encontrei, a Pagar.me mudou de plataforma (Gupy -> Greenhouse). Na nova plataforma não possui essa vaga disponível:

https://boards.greenhouse.io/pagarme/

**Comment by samycici** [comment]
oi pessoal, conseguimos preencher as vagas, @PauloGoncalvesBH tô fechando a vaga aqui!
