### ISSUE TITLE
[Porto Alegre] Analista de Qualidade JR na KingHost

### ISSUE THREAD

**Issue by isabelaschnorr** [qa-brasil/vagas#70]
#15  Descrição da vaga

A pessoa QA terá a oportunidade de trabalhar em times ágeis com equipe de desenvolvimento, sendo referência em qualidade. Estamos à procura de profissionais com experiência em testes automatizados que sejam capazes de trabalhar com autonomia propondo e gerindo soluções colaborativas.

 Principais responsabilidades:
- Análise de Requisitos;
- Criar automação para diferentes camadas da aplicação;
- Ensinar pessoas desenvolvedoras a executarem testes funcionais e automatizados;
- Documentar processos e estratégias utilizadas;
- Disseminar a importância da Qualidade do Software para toda a equipe;
- Comunicar-se com PO, pessoas desenvolvedoras e clientes para obter conhecimento técnico e funcional;
- Trabalhar próximo a pessoas desenvolvedoras, analistas de negócios, outros QAs em um ambiente altamente colaborativo;
- Coletar métricas quantitativas e qualitativas para melhorar a cobertura e a eficácia dos testes dos produtos;
- Influenciar e inspirar a sua equipe.

## Local de trabalho

Porto Alegre - Rio Grande do Sul

## Requisitos da vaga

Requisitos Flexíveis:
- Experiência com desenvolvimento de testes de software;
- Experiência em análise de cenários de testes;
- Experiência em frameworks/ferramentas de testes (Jenkins, Selenium, Cucumber, Specflow, JUnit, Jasmin, Mocha, Chai, Postman);
- Conhecimento de ferramentas Atlassian (JIRA, Confluence, Stash);
- Compreensão de todo o processo de desenvolvimento, desde o levantamento de necessidades até a entrega;
- Habilidade em priorizar bugs, identificar a causa-raíz e sugerir ações corretivas;
- Sentir-se confortável trabalhando próximo a pessoas desenvolvedoras, analistas de negócios e clientes em um ambiente altamente colaborativo;
- Capacidade de influenciar a sua equipe e seu cliente;
- Conhecimento e experiência com automação de testes e capacidade para detectar o que deve ser automatizado;
- Experiência com manutenção e evolução do ambiente de teste legado usando práticas de integração contínua;
- Noções de gerenciamento de configuração, como o SVN e Git;
- Já ter familiaridade com a cultura e metodologias ágeis.

**Desejáveis**
Ensino Superior concluído ou em andamento em Ciência da Computação, Sistemas de Informações e áreas afins.

## Forma de contratação

CLT

## Benefícios da empresa

- Horário flexível
- Possibilidade de trabalho remoto eventual
- Assistência médica e odontológica
- VT
- VA/VR
- Massoterapia 1x por semana
- Fisioterapia
- Ginástica Laboral
- Yoga
- GymPass (subsídio para atividade física)
- Parcerias para cursos (como Alura)
- Seguro de vida
- Excelente ambiente de trabalho :)

## Sobre a empresa

Já imaginou trabalhar numa das melhores empresas para se trabalhar?

Somos uma das maiores empresas de hospedagem de sites do Brasil com mais de 300 mil sites hospedados, e aproximadamente 60 mil clientes, data centers no Brasil e sede em Porto Alegre (RS). Por sete anos consecutivos, fomos eleitos como uma das 100 melhores empresas para se trabalhar no segmento de TI e Telecom no Brasil.

Nossa cultura é orientada por 6 valores

› Comprometimento

› Simplicidade

› Excelência

› Integridade

› Gratidão

› Evolução

## Como se candidatar

Por favor, enviar email para isabela.schnorr@kinghost.com.br com o seu CV anexado - Enviar no assunto: Vaga QA JR

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 14 dias após cada processo.

E-mail para contato em caso de não haver resposta: isabela.schnorr@kinghost.com.br

## Labels
- Alocado
- CLT
- Júnior

- Rio Grande do Sul

**Comment by Daniray2008** [comment]
Ola, a vaga teria alguma possibilidade PJ e remota?

**Comment by PauloGoncalvesBH** [comment]
@Daniray2008
Recomendo mandar e-mail para isabela.schnorr@kinghost.com.br ou chamar a Isabela no linkedin: https://www.linkedin.com/in/isabelaschnorr

Estou torcendo para você conseguir uma oportunidade de QA JR 😊😊

**Comment by Daniray2008** [comment]
opa muito obrigada pela ajuda
