### ISSUE TITLE
[Rio de Janeiro] Estagiário de Testes na  RADIX Engenharia e Software

### ISSUE THREAD

**Issue by fsoaresqa** [qa-brasil/vagas#71]
## Descrição da vaga

- Propor melhoria com base em feedbacks e revisões por par;

- Fazer reporte de status de testes para líderes;

- Gerar e monitorar indicadores de eficiência e prazo de entrega;

- Criação de Casos de Teste e Plano de Teste;

- Reporte de defeitos;

- Criação de relatórios de teste.

## Local de trabalho

Rio de Janeiro - RJ

## Requisitos da vaga

**Desejáveis**
- Conhecimento em criação de plano de testes e casos de teste.

**Diferenciais**
CTFL;
Inglês;
Comunicação com clientes;
BDD;
Agilidade;
Automação;
Conhecimento da ferramenta ALM (IBM).

## Forma de contratação

Estágio

## Benefícios da empresa
Vale Transporte;
Vale Refeição;
Plano de Saúde e Odontológico;
Plano de Incentivo;
﻿Programa de Desenvolvimento Profissional, entre outros benefícios.

## Sobre a empresa

SEJA BEM-VINDO À RADIX
Ser radixiano é fazer acontecer! Se você é apaixonado por tecnologia e gosta de superar desafios de maneira colaborativa, tem um lugar no nosso time te esperando. Aqui, a gente investe em criatividade, diversidade e capacitação para transformar conhecimento técnico-científico em resultados.

O que fazemos?

Oferecemos serviços e soluções altamente qualificados e com independência tecnológica para atender as principais indústrias de processo do Brasil e do mundo. Estamos presentes nos mercados de Óleo & Gás, Petroquímico, Químico, Metais e Mineração, Papel e Celulose, Alimentos e Bebidas, Geração de Energia e Mídia e Entretenimento.

## Como se candidatar

https://radix.gupy.io/jobs/245489
Em caso de dúvidas podem entrar em contato via email: rh@radixeng.com.br

## Labels
- Alocado
- Remoto
- Estágio

- Rio de Janeiro

**Comment by PauloGoncalvesBH** [comment]
@fsoaresqa 
Uma dúvida que possíveis candidatos podem ter: Essa vaga é remota ou presencial?

**Comment by Daniray2008** [comment]
Eu queria atuar home office, tem essa possibilidade?

**Comment by uLucasFraga** [comment]
@fsoaresqa consegue responder?

**Comment by fsoaresqa** [comment]
@Daniray2008 Por enquanto estamos trabalhando remotamente e ainda não temos uma data para retornar para o escritório.
A entrevista é online também.

**Comment by Daniray2008** [comment]
Otimo, me inscrevi, eu sou de Sao Paulo, entao se tiver essa opotunidade de manter remoto seria otimo, Obrigada pela resposta

**Comment by fsoaresqa** [comment]
@Daniray2008 adicionei o email do rh na issue caso tenha mais dúvidas =)
