### ISSUE TITLE
[Rio De janeiro ] Tester na RADIX Engenharia e Software 

### ISSUE THREAD

**Issue by fsoaresqa** [qa-brasil/vagas#72]
## Descrição da vaga

Temos sede por transformar nosso conhecimento técnico-científico em respostas para problemas complexos do mundo da engenharia e software.

Precisamos de pessoas ágeis, éticas, comprometidas com a entrega e que estejam em constante busca por aprendizado e novos desafios. Queremos essas pessoas para compor o nosso time e, juntos, tornarmos a Radix uma empresa Top of Mind no que diz respeito à inovação e soluções tecnológicas pelos diversos setores da indústria.

Estamos expandindo e tornando a nossa presença cada vez mais poderosa! Que tal fazer parte disso?

Como Tester, você será responsável por:

Elaboração de Plano de Testes e Casos de Teste;
Reporte de defeitos e geração de evidências;
Automatização de testes;
Elaboração de Status de testes;
Liderança técnica de equipe de testes;
Testes de aceitação com o cliente.

## Local de trabalho

Rio de janeiro - RJ

## Requisitos da vaga

**Desejáveis**
Experiência com especificação de testes (plano e casos)
Experiência com Postman
Experiência com JMeter
Inglês Intermediário/Avançado - Conversação e Escrita

## Forma de contratação

CLT

## Benefícios da empresa

Vale Transporte;
Vale Refeição;
Plano de Saúde e Odontológico;
Plano de Incentivo;
﻿Programa de Desenvolvimento Profissional, entre outros benefícios.

## Sobre a empresa

SEJA BEM-VINDO À RADIX
Ser radixiano é fazer acontecer! Se você é apaixonado por tecnologia e gosta de superar desafios de maneira colaborativa, tem um lugar no nosso time te esperando. Aqui, a gente investe em criatividade, diversidade e capacitação para transformar conhecimento técnico-científico em resultados.

O que fazemos?

Oferecemos serviços e soluções altamente qualificados e com independência tecnológica para atender as principais indústrias de processo do Brasil e do mundo. Estamos presentes nos mercados de Óleo & Gás, Petroquímico, Químico, Metais e Mineração, Papel e Celulose, Alimentos e Bebidas, Geração de Energia e Mídia e Entretenimento.

## Como se candidatar

https://radix.gupy.io/jobs/235519?jobBoardSource=gupy_public_page
Em caso de dúvidas podem entrar em contato via email: rh@radixeng.com.br

## Labels
- Alocado
- Remoto
- CLT

Rio de Janeiro RJ

**Comment by PauloGoncalvesBH** [comment]
@fsoaresqa 
Essa vaga é remota ou presencial? Pergunto pois tem as 2 informações na descrição.

**Comment by fsoaresqa** [comment]
> r

Eu deixei as duas informações pois nesse momento estamos remoto e a empresa está estudando a possibilidade de permanecer assim pro futuro.
