### ISSUE TITLE
[São Paulo] QA Pleno na 5A Attiva

### ISSUE THREAD

**Issue by helenmatos** [qa-brasil/vagas#73]
## Descrição da vaga
Estamos procurando um(a) profissional para atuar na equipe de QA, analisando escopos, documentações e problemas, desenvolvendo plano de testes, executando casos de testes, reportando bugs e automatizando testes.  

## Local de trabalho

Remoto / Escritório, Rua Arizona - São Paulo SP

## Requisitos da vaga

- Ter experiência com planejamento e execução de Teste de Integração, Funcional e de Regressão;
- Atuação com metodologias ágeis;
- Experiência com projetos de desenvolvimento de softwares corporativos para web;
- Conhecimento de processos e ferramentas para automatização de testes; 
- Detalhista e observador;
- Excelente comunicação oral e escrita;
- Graduação completa em Engenharia de Software, Ciência da Computação, Sistema da Informação e afins;
- Forte senso de dono – incluindo solução de problemas e pensamento questionador; 
- Iniciativa, senso de urgência e paixão por desafios inovadores e complexos. 

**Desejáveis**
- conhecimentos em selenium
- conhecimentos em capybara

**Diferenciais**
Certificações na Área de Qualidade; 
Execução na Automatização de testes. 

## Forma de contratação

PJ ou CLT

## Como se candidatar

- Por favor envie um email para danielle.matuda@5aattiva.com.br com seu CV anexado - Enviar no assunto: Vaga do QA-Brasil

## Labels
- Alocado
- Remoto
- CLT
- PJ
- Pleno
- Sênior

- São Paulo - SP

**Comment by PauloGoncalvesBH** [comment]
@helenmatos Algumas dúvidas que podem ser interessantes para possíveis candidatos:
- Essa vaga tem a opção tanto de remoto quanto presencial?
- Se a pessoa optar por trabalhar 100% remoto é necessário morar em SP?

**Comment by Daniray2008** [comment]
Ola gostaria de saber se teria uma possibilidade para junior remoto?
