### ISSUE TITLE
[Remoto] QA na VipCommerce

### ISSUE THREAD

**Issue by gabrielhws** [qa-brasil/vagas#76]
## Descrição da vaga

Buscamos QAs para atuar full-time 100% remoto na VipCommerce.
Estamos avaliando perfis: júnior e pleno.

## Habilidades
- BDD
- Cucumber

## Local de trabalho

100% Remoto

## Requisitos da vaga

- Perfil exploratório, comunicativo e autodidata
- Ser pró-ativo e interessado em aprendizado contínuo
- Experiência em posição semelhante
- Ser engajado em pequenos times, clima de startup e negócios que crescem de maneira acelerada (pouca zona de conforto / Lean Startup)
- Bons conhecimentos em testes de caixa preta e caixa branca
- Conhecimentos em Cucumber, Selenium e Ghost Inspect
- Conhecimentos em BDD

**Diferenciais**

- Habituado em trabalhar em times ágeis
- Experiência com automação de testes
- Habituado em trabalhar em times remotamente distribuídos
- Trabalhe com automação de testes

## Forma de contratação

- PJ ou CLT

## Benefícios da empresa

- Vale alimentação
- Plano Saúde Unimed
- Boa flexibilidade de horários de trabalho
- Subsídio de cursos e eventos em determinadas periodicidades
- 100% Home Office

## Sobre a empresa

A VipCommerce nasceu dentro de um supermercado e com vários anos de experiência no segmento varejista, entendemos o dia-a-dia do setor. E, prevendo que a venda online seria um progresso natural para os supermercados, transformamos nosso conhecimento em uma solução completa e robusta para habilitar as lojas tradicionais a venderem online.

## Como se candidatar

- Candidatar-se em: [https://bit.ly/3eX9Qgw](https://bit.ly/3eX9Qgw)

## Labels

- Remoto
- CLT
- PJ
- Júnior
- Pleno
- Minas Gerais

**Comment by PauloGoncalvesBH** [comment]
@Daniray2008 essa oportunidade deve te interessar.

**Comment by Daniray2008** [comment]
Opa, Muito bom Paulo, Muito Obrigada por lembrar de mim!!!

**Comment by FranklinHenriques** [comment]
CLT Júnior , SÃO PAULO
