### ISSUE TITLE
[REMOTO BR] QA na Hypesoft

### ISSUE THREAD

**Issue by Gabihype** [qa-brasil/vagas#962]
## Descrição da vaga

A vaga é para atuar com a Hypesoft na maior corretora de criptoativos do Brasil, atuando como QA PL para projetos relacionados ao mercado de criptoativos.

## Local de trabalho

- 100% Remoto

## Requisitos da vaga

**Obrigatórios**
•	Experiencia com Testes Automatizados;
•	Testes Regressivos e stress;
•	Experiencia com JMeter e K6

**Desejáveis**
•	Conhecimento em Cypress;

## Forma de contratação

PJ

## Sobre a empresa

Somos a Hypesoft uma empresa de consultoria e serviços de TI.
Atuamos com 3 pilares: Outsourcing, hunting e fabrica de software.

## Como se candidatar

- Por favor envie um email para gabriella.araujo@hypesoft.com.br com seu CV anexado - Enviar no assunto: Vaga de QA

## Labels

- PJ
- Pleno (Acima de 3 anos)

- 100% Remoto

**Comment by GraceMaryQA** [comment]
Boa tarde !! Enviei pro seu email.

**Comment by RodrigoJose-Silva** [comment]
Grace, boa noite!
Não consegui entender o e-mail recebido...pois consta apenas a msg acima "Boa tarde !! Enviei pro seu email.
Poderia me dar mais detalhes do que se refere?

**Comment by GraceMaryQA** [comment]
> Graça, boa noite! Não consegui entender o e-mail recebido...pois consta apenas a msg acima "Boa tarde !! Enviei pro seu email. Poderia me dar mais detalhes do que se refere?
 

Boa noite !
Eu enviei um e-mail para o e-mail da descrição da vaga : " gabriella.araujo@hypesoft.com.br"
Contendo a mensagem no assunto conforme descrito na vaga, me apresentando para oportunidade e com meu currículo em PDF.

Provavelmente o senhor recebeu um e-mail, informando que eu comentei a publicação aqui no Github. 

Mas me coloco à disposição para mais informações sobre meu perfil e atuação como QA, caso o senhor seja um dos responsáveis pela vaga de trabalho em questão.

**Comment by RodrigoJose-Silva** [comment]
Grace, boa noite!

Não...eu não tenho nenhuma ligação com com a vaga em aberto. Porém, desde já lhe desejo sorte em sua jornada!

**Comment by PauloGoncalvesBH** [comment]
@RodrigoJose-Silva abra a issue para entender a mensagem da Grace. https://github.com/qa-brasil/vagas/issues/962
