### ISSUE TITLE
[Cascavel/PR] QA na Aprova Digital

### ISSUE THREAD

**Issue by lisia-matos** [qa-brasil/vagas#987]
### Role

O Analista de Qualidade (QA) é responsável por verificar e garantir que o software entregue esteja com o funcionamento correto e livre de bugs, de forma a antecipar problemas antes do lançamento de novas funcionalidades. Também é responsável por escrever e implementar testes automatizados que sejam capazes de automatizar o processo de verificação constante de bugs e falhas, garantindo o funcionamento correto e padronizado do sistema. O QA responde ao Engineering Manager (Scrum Master).

## Local de trabalho
- 100% Remoto

## Responsabilidades

**Primárias:**
- Desempenhar um papel de liderança dentro do time de qualidade;
- Elaborar planos e casos de testes (funcionais, exploratórios, regressão, carga e automatizados);
- Desenvolver scripts de testes de alta qualidade;
- Validar configuração de ambiente necessário para realização de testes;
- Identificar possíveis gargalos na automação;
- Dominar técnicas e conceitos como Clean Code e SOLID;
- Revisar e implementar novos tipos de testes, tanto manuais como automatizados.

**Secundárias:**
- Construir e auxiliar no desenvolvimento de testes automatizados;
- Elaborar e executar planos de QA que reduzam o lead time das issues e tempo até o software entrar em ambiente de produção;
- Escrever e implementar testes automatizados utilizando o Cypress ou similar — a meta da companhia é atingir um coverage de 100% do caminho crítico do nosso usuário até o Q2 de 2022;
- A partir das ações executadas no plano, implementar e manter um modelo de Continuous Delivery, com base na alta confiança da qualidade e coverage dos testes automatizados, implementada no github actions;
- Avaliar se as entregas dentro da engenharia resolvem os problemas dos clientes a partir da visão do Product Manager;
- Avaliar se as entregas dentro da engenharia resolvem os problemas dos clientes a partir da visão de Produto. Verificar se a Regra de Negócio e UX apresentadas pelo Software Engineer responsável pela tarefa é condizente com o que foi solicitado por Produto;
- Avaliar se os códigos produzidos seguem o padrão de qualidade estabelecido pelo Gerente de Engenharia e Tech Leads, sendo um double check do já implementado code review peer to peer;
- Auxiliar na implantação e escolha de novas ferramentas a serem utilizadas no dia-a-dia do time, Propondo soluções de melhorias de trabalhos e fluxos.

## Requisitos da vaga

- Graduação completa ou em andamento - Analista de Sistemas, Ciência da Computação, Engenharia da Computação, e áreas afins;
- Experiência como Automation Engineer/ Quality Assurance/ Analista de Qualidade (QA);
- Ter comunicação clara, direta e organizada;
- Conhecimento de metodologias ágeis;
- Conhecimento em Angular 10, NodeJS e MongoDB;
- Conhecimento na área de testes e qualidade de software;
- Conhecimento em técnicas e estratégias de teste;
- Comunicação para transmissão dos problemas e desafios encontrados;
- Cadência e confiabilidade de trabalho (ou seja, que o seu time possa contar com você);
- Ter domínio em cypress;
- Ter domínio em Javascript/Typescript.

**Diferenciais**

- Dominar dinâmicas e ferramentas de gestão de produtos (ex: ferramentas de priorização e discovery);
- Vivência no ambiente de startup;
- Experiência com automatização de SaaS.

## Forma de contratação
 CLT

## Benefícios da empresa

Vale-alimentação flexível (Swile/Vee);
Plano Odontológico;
Seguro de vida;
Crescimento financeiro à medida que a empresa cresce;
Day-Off para seu aniversário;
Boteco do Aprova;
Cursos in-company;
Trabalho Híbrido;
Ambiente informal, descontraído e com pessoas incríveis;
​Aprendizados e desafios diários;

## Range Salarial

Estamos trabalhando com uma faixa salarial de R$ 4k a R$ 13k.

## Sobre a empresa

Nós vamos simplificar a relação do governo com os cidadãos.

O Aprova Digital é uma startup de software como serviço (SaaS) que há quatro anos vem criando ferramentas inovadoras para o governo. Somos uma plataforma completa, a qual torna digital os processos de alvarás e licenciamentos das prefeituras, permitindo que todos os trâmites perpassem pelo nosso software sem empilhar papeladas na mesa do secretário. Nossa equipe tem a chance de construir algo totalmente novo, o que muda a maneira como o governo presta serviço ao cidadão.

Cultura e Pessoas:

Os objetivos do Aprova Digital refletem diretamente em nossa Cultura e Workflow. Palavras como transparência, comunicação, confiança, curiosidade e paixão são são coisas que não abrimos mão — do desenvolvimento à venda, do backoffice ao atendimento.

Nosso principal valor é que as pessoas sempre vêm em primeiro lugar. Por isso, é nossa prioridade criar um ambiente saudável e cheio de oportunidades para todos os times e posições. Esse é o único caminho para que nossas pessoas sejam bem-sucedidas.

Nossa máquina funciona porque somos produtivos e animados. Os condutores trabalham e se divertem muito. Nossos bate-papos no Slack estão constantemente fervilhando de piadas e convites para eventos, e você não terá dificuldade em encontrar um hobby ou interesse que não esteja representado.

Aqui, não existe inacessibilidade, somos uma harmônica chuva de ideias, do CEO e Heads aos recém-chegados, tudo se integra. Como a equipe é multicultural, existem pessoas com todos os tipos de especialidades, e sempre há algo para aprender uns com os outros.

## Como se candidatar
Poderá se candidatar  a vaga através do link: https://aprovadigital.gupy.io/jobs/1707159

## Labels
- CLT
- Pleno
- Sênior
- Especialista
- Remoto
- Paraná
- Cypress

**Comment by santosvini** [comment]
a vaga se encontra encerrada, através do redirect

**Comment by lisia-matos** [comment]
vaga encerrada :]


Segue link da nova posição que temos em aberto Analista de Qualidade (sênior) - QA Playwright + Javascript + CI/CD [São Paulo/SP] [https://aprovadigital.gupy.io/jobs/7915514]
